### ISSUE TITLE
Should we modify the API for NNLS and lstsq inversions to make it less confusing?

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#109]
Currently, the regularised least squares and non-negative least squares inversion routines in `cherab.tools.inversions` take a parameter `alpha` and an optional regularisation matrix `tikhonov_matrix`.  If `tikhonov_matrix` is not provided then the regularisation matrix is `alpha` times the identity matrix. If `tikhonov_matrix` is provided, it is used as the regularisation matrix and `alpha` is not used at all. In this case the caller is responsible for scaling the regularisation matrix before passing it into the function.

It seems to me that the following behaviour would be more consistent:

- If `tikhonov_matrix` is `None`, it is set internally to the identity matrix.
- The regularisation matrix is always `alpha` times `tikhonov_matrix`.

This would then always make alpha control the relative importance of the measurement and regularisation, rather than only doing so when `tikhonov_matrix` is not supplied. I'm worried that the current behaviour is not intuitive. Should we change this?

**Comment by mattngc** [comment]
I agree, this change would make the API cleaner. Would be happy to accept a PR with this change.

**Comment by mattngc** [comment]
Closed with PR #110 contributed by @jacklovell.
