### ISSUE TITLE
equilibrium specimen in CHERAB core

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#120]
It would be nice if there was an example of an equilibrium reconstruction to use for examples, tests and code development. What do you think?

**Comment by mattngc** [comment]
I agree, I think this would be a good idea. It might be best if it doesn't resemble an actual machine. Maybe I'll shrink and distort a real equilibrium to get something we can work with.

**Comment by Mateasek** [comment]
If you want to have an equilibrium which does not belong to any machine, then I could provide one generated by Fiesta. According to my desk-mate he would generate one, if I provide him with him some basic parameters.

**Comment by mattngc** [comment]
haha, lol. I've just spent most of the morning generating one. Let's see if that one turns out ok, otherwise I might indeed ask for your help there.

**Comment by mattngc** [comment]
Closed with ae7ac87.
