### ISSUE TITLE
Bolometry workflow examples

### ISSUE THREAD

**Issue by mattngc** [cherab/core#122]
We now have a reasonable collection of classes and workflow functions for bolometry and soft xrays, many of which are complementary to ToFu. But unfortunately we don't have any good tutorials. We should add some workflow examples for:

- modelling bolometer detectors
- creating suitable radiation functions
- calculating sensitivity matrices
- performing inversions within CHERAB and recommendations for coupling to ToFu

**Comment by jacklovell** [comment]
Closed by #161
