### ISSUE TITLE
EFITEquilibrium not properly dealing with missing limiter polygon

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#125]
When passing `limiter_polygon=None` into `EFITEquilibrium`, I would expect the generation of the `inside_limiter` mask to be skipped (as suggested by `_process_polygons`). However, in `__init__` the polygon is converted to a numpy float64 array, which in turn converts `None` to `nan`. This then causes the `is None` check in `_process_polygons` to fail, and so Cherab tries to build a limiter mask for a limiter of value `nan`.

We should either:

1. Only convert the limiter polygon to an array if it is not `None`.
2. Check in `_process_polygons` if the limiter polygon is `nan` rather than `None`.

I personally prefer option 1, as leaving undefined options as `None` and using the `is None` idiom seems more Pythonic. It would however mean treating the limiter differently to the other sequence-like inputs when converting them to arrays in `__init__`. Though considering the limiter is the only one which is allowed to be `None` already, perhaps this isn't such a bad thing.

**Comment by Mateasek** [comment]
I also think 1. is nicer option. It is cheaper/easier to check if it is None than array of nans (and it is more pythonic as you said) plus storing whole array of nans is quite redundant.

**Comment by CnlPepper** [comment]
It's a bug, it should not be attempting to convert a None into an array. I'll fix it when I can.

**Comment by mattngc** [comment]
Closed in PR #134.

**Comment by sgibson-mse** [comment]
Bug still present with limiter polygon reading as nans. Adding if test before array creation fixes this bug.
