### ISSUE TITLE
Clamping Interpolators at edges of range

### ISSUE THREAD

**Issue by mattngc** [cherab/core#128]
I've seen numerous cases where CHERAB's core interpolators can end up producing negative values, despite the input data only being defined from [0, max]. This often seems to appear when working with beam attenuation rates, or radiation maps. I think its because of the swing in cubic interpolation. We should add an optional keyword argument to clamp the interpolation to the supplied data range.

**Comment by Mateasek** [comment]
I also encountered this when working on ionization balance (I was getting negative densities), but I thought that the oscillations are just the nature of the cubic interpolators (for example when the function 1st and 2nd derivatives are high) and switched to linear to stay on the safe side.

**Comment by mattngc** [comment]
Yes, its true that this is what interpolators will naturally do if they are cubic. But this doesn't mean we can't add some nice utilities to prevent users from being stung by this issue. I think we could add a keyword option to clamp outside the data domain or add an external FunctionXD wrapper for clamping. Personally I think this might be a better option.

**Comment by Mateasek** [comment]
I just hit this problem again, when using map3d equilibrium function. I feed it 1d linear interpolator made using only positive values (densities). The 1d interpolator does not give negative values, but when the AxisymmetricMapper is made out of it, it does provide negative values.

**Comment by Mateasek** [comment]
To correct the previous comment, it is indeed caused by cubic interpolator in equilibrium mappers.

**Comment by CnlPepper** [comment]
I've added clamp functions that can be use to clamp the input and output of any arbitrary function. As you seem to need these quickly, I've committed the code without docstrings. @mattngc could you add the docstrings?

Usage:

```
from cherab.core.math import ClampOutput1D, ClampInput1D

# prevent function output going below zero
clamped_fn1 = ClampOutput1D(myfunction, min=0.0)

# prevent input to a function going outside the range 5 to 10
clamped_fn2 = ClampInput1D(myfunction, xmin=5.0, xmax=10.0)
```

**Comment by CnlPepper** [comment]
Fixed in commit e23f72aaf79e9f32095d7ca319879ce8cdd0cef8.

**Comment by mattngc** [comment]
Hey @Mateasek, we've added these classes now and the documentation has been updated. Please give them a try and give us your feedback :) 

Still lots of work to do on documenting the whole math library...

**Comment by mattngc** [comment]
We also need to put these clamps in a few key places. Principally, the Equilibrium Interpolators and the NBI density interpolator. I will make separate issues to track these as appropriate.
