### ISSUE TITLE
Add possibility to choose interpolator degree in EFITEquilibrium map2d and map3d

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#130]
It would be nice to add an optional parameter to map2d and map3d function allowing the user to choose between linear and cubic interpolation. It could be "cubic" in default and another option could be "linear". The parameter would then switch between Interpolate1DCubic and Interpolate1DLinear.

When working on ionization balance calculations I hit a probilem that these mappers can return wrong values of element densities. One way how to prevent this is using only linear interpolation, to get rid of unwanted oscillations in interpolated profiles.

 what do you think?

**Comment by CnlPepper** [comment]
This is already possible. The mapping functions will accept a function object or a sequence. If you pass is just a list or numpy array it will interpolate them with cubic interpolation. If you want to not use the default, wrap the data in the relevant interpolator and pass it in instead.

```equilibrium.map3d(Interpolate1DLinear([...], [...])```

@mattngc this needs adding to the documentation. It is only describe at present in the equilibrium demo.

**Comment by Mateasek** [comment]
I saw that in the code, but I thought since it allows passing an array of values or an interpolating function it could also allow choosing the interpolator degree.

**Comment by mattngc** [comment]
Hmm... I think I agree with @CnlPepper here. The behavior you want is already there but just needs to be documented better. The current behavior is that the code makes the best guess based on the data you give it. If you supply a function it just uses it. If users need more control over the behavior of the function, its better they implement that themselves in the supplied function. There is potentially a lot of settings they may need to control and this would lead to an expension in the number of keyword arguments required. But we could definitely upgrade the documentation to better reflect this as an option.

**Comment by Mateasek** [comment]
I see the point, I am closing the issue.
