### ISSUE TITLE
ToroidalVoxelGrid emissivities from function is only sampling from one triangle

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#142]
The `ToroidalVoxelGrid.emissivities_from_function` method is supposed to perform a Monte-Carlo integration of a function over the voxel cross section by sampling the function uniformly over the area bounded by the voxel cross section. This means uniformly sampling from each of the triangles which make up the voxel cross section, with the number of samples for each triangle proportional to the triangle's area. However, the current implementation is not correctly calculating the area of each triangle: only a single triangle area is computed.

While fixing this behaviour, it would also be useful to move much of the functionality of `emissivities_from_function` into the `AxisymmetricVoxel` class, and then call this method once for each voxel in the `ToroidalVoxelCollection`.

**Comment by mattngc** [comment]
Fixed with PR #143.
