### ISSUE TITLE
RadiationFunction should transform to world before calling underlying function

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#153]
The function passed in to the `RadiationFunction` constructor doesn't know anything about the primitive to which it will be attached, and so can have no knowledge of that primitive's transform. It follows that any such function must be defined in the world's coordinate space. However, `RadiationFunction.emission_function` calls the function in local space, which leads to incorrect results.

The `vertical_offset` property partially mitigates this, but only works if the primitive is not translated (or rotated, if the function is not axisymmetric) in the x or y directions. It also relies on the caller to match the `vertical_offset` with the vertical shift of the primitive to which it's applied, which may not be trivial if there are multiple transforms in the parent, grandparent etc. of the primitive and is error prone.

A more robust solution would be to get rid of the `vertical_offset` property entirely and have `RadiationFunction.emission_function` transform the point to the world's coordinate system before calling the underlying function. Thoughts?

**Comment by CnlPepper** [comment]
Hi Jack,

I added a material modifier to handle circumstances like this. See:

https://github.com/raysect/source/blob/development/raysect/optical/material/modifiers/transform.pyx
https://github.com/raysect/source/blob/master/demos/materials/modifiers/transform.py

You can use this to shift the volume material around inside the primitive.

Best regards,

Alex

**Comment by jacklovell** [comment]
Thanks Alex. That worked, although I found it very un-intuitive, both to use a material modifier in the first place and then to select the appropriate transform: I basically arrived at `emitting_primitive.to_local()` by trial and error.

For the avoidance of confusion I would suggest we remove the `vertical_offset` property from `RadiationFunction` ("there should be one, and preferably only one, way to do it") and then mention in the docstring for this class that if its primitive has a non-identify transform then it should be wrapped in a `VolumeTransform` modifier else the results will be wrong.
