### ISSUE TITLE
BolometerFoil.as_sightline uses incorrect transform

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#154]
The `SightLine` observer created by `BolometerFoil.as_sightline` is given `transform=self.transform`, despite its parent being `self`. This leads to a double transform for the observer. The transform should be `None` (i.e. omitted from the instantiation call), as the sightline should have the same local coordinate system as its parent, the foil.

**Comment by mattngc** [comment]
Fixed with PR#156.
