### ISSUE TITLE
Add prescribed mathematical functions

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#160]
A number processes are can be described by usual mathematical functions. Mathematical prescriptions of these could be stored somewhere in cherab/raysect to be used in other parts of the code. They could have methods returning arrays, interpolators, Spectra and etc. It could prevent piling up of the same code.

For example, normal distribution is used for in line shape emissions, population temperatures, time evolutions and etc. The calculation of the normalized shape could in theory be reused  by all of these.

What do you think?

p.s. I tried to look if there is some kind of this source, but I couldn't find it.

**Comment by jacklovell** [comment]
I've raised a similar issue [in raysect](https://github.com/raysect/source/issues/305), which has some of the building blocks for this sort of thing but isn't quite general enough to support non-linear functions. I agree that it would be useful to have these sorts of functions implemented in Cython rather than having to rely on user-implemented, slower Python versions.

**Comment by Mateasek** [comment]
I see we have created a nice loop here :-D @CnlPepper or @mattngc could decide where it would belong more. What I hand in mind was a class looking something like this:

``` python
cdef class PrescribedFunction(FunctionxD)
    cdef double evaluate(self, double x) except? -1e999:
        ....
    cpdef Spectrum spectrum():
        ...
    cpdef double interpolator():
        ....
    cpdef double integrate():
        ....
```
there could be more methods added as necessary and inheriting methods could be in general used in codes to calculate dependent variables as well as by users to generate their arrays/spectra and etc..

**Comment by mattngc** [comment]
Hey, thanks for this idea. I think these definitely belong more in the Raysect tools. So the issue by @jacklovell is the appropriate place to collate ideas, https://github.com/raysect/source/issues/305. Please take this further over there.
