### ISSUE TITLE
Strange results using Radiance as the units in BolometerFoil

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#162]
When observing a uniformly radiating region with a bolometer foil, I would expect the radiance to be approximately the emissivity multiplied by the path length. In the simple case of a uniformly radiating torus viewed by a vertical bolometer chord, the radiance (in W/m2/sr) * 4pi should be roughly twice the minor radius of the torus.

This is indeed the case when using the `Power` units in `BolometerFoil`, then taking the pipeline result and dividing by the etendue. However, when using the `Radiance` units, the measured radiance is nearly 5 orders of magnitude too small.

For an example of this calculation, see https://github.com/jacklovell/cherab-core/blob/enhancement_bolometry_examples/demos/observers/bolometry.py.

**Comment by jacklovell** [comment]
I've found the same thing while modelling the KSTAR IRVB: power calculation looks reasonable, but the radiance is ~5 orders of magnitude too small.

**Comment by mattngc** [comment]
Ok, let's find some time to chat about this.

I'm pretty sure I remember working this out before and deciding its not a bug... probably should have written that down somewhere

**Comment by jacklovell** [comment]
To summarise our discussion earlier (and to ensure this is actually written down somewhere this time):

The bolometer is based on a `TargettedPixel`, and for observations it is assumed that the pixel's sampling volume subtends a solid angle of 2pi. An actual bolometer system also has an aperture which reduces the solid angle subtended by the detector, so a scaling factor needs to be applied to the reported radiance. I think that the value reported by the BolometerFoil's radiance pipeline, scaled by `2pi / detector_solid_angle`, should match the power reported by the power pipeline divided by the bolometer's etendue from the `calculate_etendue` method (though I still need to check this).

I've also found some historic code for MAST-U where we worked around this by scaling the radiance weights by `sum(line of sight radiance weights) / sum(volumetric radiance weights)`. The code's comment mentions this solid angle issue as the reason for the scaling, but I can't find a mathematical justification for it.

I suspect that the raysect change https://github.com/raysect/source/commit/938cc595499d58d5cc23ac3c6cc67b499a2ce09d was also motivated by this discussion previously.

Of course, since the value reported by the BolometerFoil's radiance pipeline is not actually the radiance bolometry people deal with, it raises the question of whether a BolometerFoil should support `units == "Radiance"` at all. And if it should, should there be some conversion from raysect's radiance quantity to the one bolometrists expect, and should this be done automatically or just explained in the documentation and left to users?

**Comment by mattngc** [comment]
Ah, the MAST documentation would make sense. I think we previously encountered this when comparing CHERAB output to Antony Field's results. And I remember having a long argument with him on the white board which eventually resolved it, if only I'd copied it!

I'd be very reluctant to change the definition of Radiance anywhere. If you work through the Observer maths you will find it is the Radiametric definition of Radiance for volumetric observers.  The issue is that bolometry people usually only work in terms of infinitesimal sightlines. I think it would be better to give a new name for this third quantity and provide an optional calculation path to it.

Its all coming back to me now. I think I could do the derivation quickly if push comes to shove.

**Comment by CnlPepper** [comment]
I want to add that the radiance pipeline in raysect returns the mean radiance striking the detector surface, I don't consider it a particularly useful value in general.

Radiance is essentially the wrong unit to be working in if looking at a bolometers (or any other diagnostic system) response. I see no need for any radiance calculation except to perform an approximate comparison with old single ray models.

**Comment by jacklovell** [comment]
@mattngc I would very much like to see that derivation, as I can't for the life of me work out the justification for this scaling factor that we used previously. I have just checked again though, and it does scale the sensitivity matrices correctly for both the JET and MAST-U bolometry systems. I suppose radiance is a more appropriate unit than power for idealised pinhole detectors (indeed, a `Sightline` observer viewing a uniform volume measures about what I'd roughly expect the radiance to be based on the path length through the volume), but for "real" detectors power seems to be the more natural unit.

In bolometry, users have historically been interested in the line-integral of an assumed-isotropic emissivity. If a bolometer detector has a power P incident on it, the quantity of interest is:

![equation](https://latex.codecogs.com/svg.latex?P_L%3D%5Cint%5Cepsilon%5C%2C%5Cmathrm%7Bd%7Dl%3D%5Cfrac%7B4%5Cpi%20P%7D%7BE%7D)

(The 4π comes from the isotropic assumption, dl is a small step along the line of sight and E is the etendue). This has been variously called "intensity", "brightness", "radiance" and probably others, none of which is likely the correct radiometric term. Its use has been popular because it couples nicely to length matrix calculations for tomography, which have again historically assumed an idealised pinhole detector.

Since we can calculate geometry matrices which already incorporate the 3D structure of the detector and directly go between emissivity and measured power, I think the justification for this "intensity/brightness/radiance" value doesn't really apply in Cherab. If people really want to use it (for example to couple to external codes), it's easy enough to calculate by dividing the measured power by the etendue.

For the avoidance of confusion, I propose removing  the "radiance" units from the `BolometerFoil` object, and indeed any other object modelling this sort of system (IRVB, SXR, AXUV) which we implement in future. These types of detector would only ever report the incident power, and conversions to other units such as "brightness" would be left to the end user. I also propose that the `Sightline` observer returned by `BolometerFoil.as_sightline` uses a `RadiancePipeline0D` as its pipeline, which would mean it returns observations in different units to the parent `BolometerFoil` object. This would need to be clearly documented, but I don't think it makes sense to report power on a `Sightline` observer in this instance.

Do you agree with making these changes?

**Comment by mattngc** [comment]
ok, I'm setting some time asside this week (weekend probably) to redo the derrivation.

Not sure I agree with all the changes. Certianly for a Sightline Observer it makes sense to remove the option to return power... its not physical. But the other changes I'm less convinced on. Radiance is a legitimate unit and it does have legitimate uses. The problem is that few people understand how to use this quantity correctly. Its prevalent in the bolometer/optics community because its legitimately  convenient when comparing sightlines. And this is an easy comparison to do with simple calculations. The problem is that when you go to an inherrently 3D system the value becomes a weighted sum over an ensemble of sightlines... but the units are still the same. Hence comparins a single sightline with an ensemble of sightlines never makes sense. This is the gist of the derrivation.

**Comment by jacklovell** [comment]
Here is the derivation for the required correction factor. I'll also add a note in the `BolometerFoil` documentation to highlight the different interpretations of "radiance" in Cherab/Raysect and the bolometry community, which will hopefully avoid confusion in the future.

For a 3D observer like the `BolometerFoil(TargettedPixel)` class, Raysect calculates the mean radiance: 

![](https://latex.codecogs.com/svg.latex?%5Coverline%7BL%7D%20%3D%20%5Cfrac%7B%5CPhi%7D%7BA%5COmega%7D)

The power Φ is calculated by integrating the spatially-dependent radiance over the area of the pixel and the _entire_ solid angle subtended by the pixel:

![](https://latex.codecogs.com/svg.latex?%5CPhi%20%3D%20%5Cint_0%5E%7B%5Comega_%7B2%5Cpi%7D%7D%5Cmathrm%7Bd%7D%5Comega%20%5Cint_0%5EA%20%5Cmathrm%7Bd%7DA%20%5C%2C%5Ccos%5Ctheta%20%5C%2CL%28%5Cmathbf%7Bx%7D%2C%20%5Comega%29)

Here, ![](https://latex.codecogs.com/svg.latex?%5Comega_%7B2%5Cpi%7D%20%3D%202%5Cpi) is the solid angle subtended by the pixel and *x* is a point on the pixel's surface. This is all described in the Raysect documentation on Observing Surfaces: https://raysect.github.io/documentation/observers.html#observing-surfaces. For the `BolometerFoil(TargettedPixel)` class, Ω = 2π by definition: the pixel is sensitive to light arriving from any point on a hemisphere, ignoring details of the manufacture of bolometer sensors with recessed foils.

Now, the aperture (`BolometerSlit`) in the bolometer system means that the radiance L(**x**, ω) is only nonzero for solid angles smaller than that subtended by the slit:

![](https://latex.codecogs.com/svg.latex?L%28%5Cmathbf%7Bx%7D%2C%20%5Comega%29%20%3D%20%5Cleft%5C%7B%20%5Cbegin%7Bmatrix%7D%20L%28%5Cmathbf%7Bx%7D%2C%20%5Comega%29%20%26%20%5Comega%20%5Cle%20%5Comega_%7Bslit%7D%20%5C%5C%200%20%26%20%5Cmathrm%7Botherwise%7D%20%5Cend%7Bmatrix%7D%5Cright.)

This means that the integral of the radiance over the full 2π solid angle of the pixel is the same as the integral over the solid angle subtended by the slit:

![](https://latex.codecogs.com/svg.latex?%5CPhi%20%3D%20%5Cint_0%5E%7B%5Comega_%7B2%5Cpi%7D%7D%20%5Cmathrm%7Bd%7D%5Comega%20%5Cint_0%5EA%20%5Cmathrm%7Bd%7DA%20%5Ccos%5Ctheta%20L%28%5Cmathbf%7Bx%7D%2C%20%5Comega%29%20%3D%20%5Cint_0%5E%7B%5Comega_%7Bslit%7D%7D%20%5Cmathrm%7Bd%7D%5Comega%20%5Cint_0%5EA%20%5Cmathrm%7Bd%7DA%20%5Ccos%5Ctheta%20L%28%5Cmathbf%7Bx%7D%2C%20%5Comega%29%20%3D%20%5CPhi_B)

When comparing the radiance along a single line of sight with an aperture-detector system like a bolometer, it's conventional to consider the average radiance only over the region subtended by the aperture:

![](https://latex.codecogs.com/svg.latex?%5Coverline%7BL_B%7D%20%3D%20%5Cfrac%7B%5CPhi_B%7D%7BA%20%5Comega_%7Bslit%7D%7D)

(In the limit A -> 0 and ωslit -> 0 this becomes the radiance for a sightline). Since ![](https://latex.codecogs.com/svg.latex?%5CPhi_B%20%3D%20%5CPhi), we can then relate ![](https://latex.codecogs.com/svg.latex?%5Coverline%7BL%7D) to ![](https://latex.codecogs.com/svg.latex?%5Coverline%7BL_B%7D):

![](https://latex.codecogs.com/svg.latex?%5Coverline%7BL_B%7D%20%3D%20%5Cfrac%7B%5CPhi_B%7D%7BA%20%5Comega_%7Bslit%7D%7D%20%3D%20%5Cfrac%7B%5CPhi_B%7D%7BA%20%5Comega_%7B2%5Cpi%7D%7D%20%5Cfrac%7B%5Comega_%7B2%5Cpi%7D%7D%7B%5Comega_%7Bslit%7D%7D%20%3D%20%5Cfrac%7B%5CPhi%7D%7BA%20%5Comega_%7B2%5Cpi%7D%7D%20%5Cfrac%7B%5Comega_%7B2%5Cpi%7D%7D%7B%5Comega_%7Bslit%7D%7D%20%3D%20%5Coverline%7BL%7D%20%5Cfrac%7B%5Comega_%7B2%5Cpi%7D%7D%7B%5Comega_%7Bslit%7D%7D)

So, to convert from the mean radiance as reported by Cherab/Raysect (averaged over a full hemisphere) to the mean radiance of a finite approximation of a sightline (i.e. only averaged over the small solid angle subtended by the aperture), we need to scale the result by the inverse of the fractional solid angle subtended by the slit vs a hemisphere:

![](https://latex.codecogs.com/svg.latex?%5Cfrac%7B%5Coverline%7BL_B%7D%7D%7B%5Coverline%7BL%7D%7D%20%3D%20%5Cfrac%7B%5Comega_%7B2%5Cpi%7D%7D%7B%5Comega_%7Bslit%7D%7D)

_A further note:_

We can calculate the fractional solid angle by firing rays uniformly from the surface of the pixel and recording what fraction of them make it through the aperture. In fact, this is already done for the etendue calculation in `BolometerFoil.calculate_etendue`:

![](https://latex.codecogs.com/svg.latex?G%20%3D%20%5Cint_0%5E%7B%5Comega_%7Bslit%7D%7D%5Cmathrm%7Bd%7D%5Comega%20%5Cint_0%5EA%20%5Cmathrm%7Bd%7DA%20%5Ccos%5Ctheta%20%3D%20A%20%5Comega_%7B2%5Cpi%7D%20%5Cfrac%7B%5Comega_%7Bslit%7D%7D%7B%5Comega_%7B2%5Cpi%7D%7D)

Or:

![](https://latex.codecogs.com/svg.latex?%5Cfrac%7B%5Comega_%7B2%5Cpi%7D%7D%7B%5Comega_%7Bslit%7D%7D%20%3D%20%5Cfrac%7BA%20%5Comega_%7B2%5Cpi%7D%7D%7BG%7D)

So, if the etendue of the bolometer is already calculated:

![](https://latex.codecogs.com/svg.latex?%5Coverline%7BL_B%7D%20%3D%20%5Coverline%7BL%7D%20%5Cfrac%7BA%20%5Comega_%7B2%5Cpi%7D%7D%7BG%7D%20%3D%20%5Cfrac%7B%5CPhi%7D%7BG%7D)

Of course, this begs the question of why you'd ever use the radiance pipeline in Cherab instead of  using the power pipeline and dividing by the etendue, since the latter needs to be calculated in both cases for any meaningful comparisons with the "tradiational" radiance measure. But it's nice to know it can be done.

**Comment by mattngc** [comment]
Thanks Jack, great work in writing this up. I should have written it down last time we had to explain it. I think this explanation should go into a dedicated note in the Bolometry documentation. But we can now consider this issue closed.
