### ISSUE TITLE
UnityVolumeEmitter material is assigned to the voxels at initialization of ToroidalVoxelGrid even if active='all'

### ISSUE THREAD

**Issue by vsnever** [cherab/core#179]
The method `self.set_active(active)` must be called at the end of `ToroidalVoxelGrid` initialization. Otherwise, in the case of `active='all'` the `UnityVolumeEmitter` material will be assigned to the voxels by default instead of the `UnityVoxelEmitter` material (which should be assigned in this case). This leads to incorrect results until `set_active('all')` is called explicitly after initialization.

**Comment by jacklovell** [comment]
Good spot. Looks like `ToroidalVoxelCollection.__init__` is attempting to do the equivalent of `set_active`, but not doing it properly. We'll fix this.

**Comment by mattngc** [comment]
Damn... looks like another Matt-ism
