### ISSUE TITLE
Populating OpenADAS repository intermittently fails

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#185]
Following the new instructions in the documentation, this fails on my laptop:
```python
>>> from cherab.openadas.repository import populate
>>> populate()
Installing adf11/scd12/scd12_h.dat...
 - downloading ADF file 'adf11/scd12/scd12_h.dat' to '/home/jlovell/.cherab/openadas/download_cache/adf11/scd12/scd12_h.dat'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlovell/FUN/cherab/cherab_core/cherab/openadas/repository/create.py", line 382, in populate
    install_files(rates, download=download, repository_path=repository_path, adas_path=adas_path)
  File "/home/jlovell/FUN/cherab/cherab_core/cherab/openadas/install.py", line 38, in install_files
    install_adf11scd(*args, download=download, repository_path=repository_path, adas_path=adas_path)
  File "/home/jlovell/FUN/cherab/cherab_core/cherab/openadas/install.py", line 85, in install_adf11scd
    path = _locate_adas_file(file_path, download, adas_path)
  File "/home/jlovell/FUN/cherab/cherab_core/cherab/openadas/install.py", line 360, in _locate_adas_file
    urllib.request.urlretrieve(url, target)
AttributeError: module 'urllib' has no attribute 'request'
```

Looks like we should be importing `urllib.request` rather than just `urllib` in install.py. Weirdly, the exact same commands worked fine on Freia, despite a subsequent call to `urllib.request` returning the same `AttributeError`. In any case, I think giving the full path to the submodules is more robust, and is also what is done in the official urllib documentation [examples](https://docs.python.org/3.7/library/urllib.request.html#examples).

**Comment by CnlPepper** [comment]
I can't replicate the issue on any of my machines. What is your environment out of curiosity?

**Comment by CnlPepper** [comment]
Making these releases is quite a lot of faffing around at the moment, I'd like to be sure this isn't just a local issue on your machine. Can you make a clean environment and try again?

**Comment by CnlPepper** [comment]
Ok I have just managed to replicated it. It works if you use ipython, but not if you use the plain python interpreter.

**Comment by CnlPepper** [comment]
I'll make a new release in a few days, some other issues might come out of the woodwork.
