### ISSUE TITLE
Bolometer rounded corners mask sometimes fails

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#194]
I've noticed when trying some different bolometer foil geometries that applying the rounded corners mask sometimes fails to work properly: rather than just masking the corners it masks most of the foil. I think this is a numerics issue: the mask is the subtraction of elements with exactly the same height, and so sometimes rounding errors mean that coincident surfaces of the two subtracting primitives don't completely disappear from the resulting primitive.

For robustness, the primitive to be subtracted should be slightly larger than the primitive it is being subtracted from to avoid coincident surfaces.

**Comment by mattngc** [comment]
Fixed with PR #195.
