### ISSUE TITLE
Failing CI test

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#200]
One of the CI tests is failing in all recent pull requests, and is unrelated to any of them:
```
$ dev/test.sh

.....................................................................................................................................................................................................................................................................................................................................................................................F................................sss................................

======================================================================

FAIL: test_value (cherab.core.tests.test_maxwellian.TestMaxwellian)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/cherab/core/cherab/core/tests/test_maxwellian.py", line 103, in test_value

    msg='call method gives a wrong phase space density at ({}, {}, {}, {}, {}, {}).'.format(x, y, z, vx, vy, vz))

AssertionError: 0.09653280845576885 != 0.09653281333977441 within 1e-10 delta : call method gives a wrong phase space density at (-10.0, -10.0, -10.0, -1000000.0, 0.0, 0.0).

----------------------------------------------------------------------
```
The suggestion from @CnlPepper is that a recent change in Numpy or Scipy may have caused this. I propose we increase the tolerance on the `AssertAlmostEqual` test, since it appears the current tolerance is set too small and is catching rounding errors in libraries rather than depending only on the correctness of the code.

**Comment by mattngc** [comment]
I agree with this. +1

**Comment by CnlPepper** [comment]
It's odd, it looks like the underlying function being called is now only running single precision. We should probably report this to numpy/scipy. For now, dropping the accuracy level should be ok if you want to submit a patch.

**Comment by CnlPepper** [comment]
Could someone confirm this is the environment and raise a ticket with scipy? I've not got the spare capacity at the moment.

**Comment by jacklovell** [comment]
@CnlPepper I tried the same as you, with the same result (see the bugfix/maxwellian-test branch). Looks like it should be a 6 significant figures, rather than 6 decimal places, match.

**Comment by CnlPepper** [comment]
Ok so... it turns out scipy updated some of their constants: http://scipy.github.io/devdocs/release.1.4.0.html

They use the CODATA 2018 values which have an updated elementary charge: 1.602176634 e-19 compared to 1.6021766208e-19.

I'll update our values and merge. Plus reset that accuracy change.

**Comment by CnlPepper** [comment]
I've updated the constants. @Mateasek I've also fixed the exponent issue.

**Comment by jacklovell** [comment]
Updating the constants causes the unit test to fail on Scipy <1.4.0. Should we skip this test if the required Scipy version isn't recent enough?

**Comment by CnlPepper** [comment]
Ah yes.... should have added a test for the scipy version....

**Comment by CnlPepper** [comment]
I've switched the test to use explicit constants. This will address the version issue as scipy is no longer a dependency.
