### ISSUE TITLE
Add function to create slab plasma with constant plasma parameters

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#201]
This is inspired by already existing function `build_slab_plasma` generating slab plasma with evolving plasma parameters. To me it showed as useful to have quick access to a function creating slab plasma with parameters constant over the plasma volume. To me it proved as useful for tests and development, because it offers possibility to create examples which can also be characterized analytically (or at least well approximated). If it is useful for others I could make a PR for that.

**Comment by CnlPepper** [comment]
@Mateasek this would potentially be useful, feel free to submit a PR and we'll review it.

**Comment by jacklovell** [comment]
Fixed by #208
