### ISSUE TITLE
Generomak - core plasma specification

### ISSUE THREAD

**Issue by mattngc** [cherab/core#210]
Following issue #209, we need an importable core plasma specification. The example data could come from a core 1D transport solver, such as METTIS or TRANSP. The profiles included should make sense for the example equilibrium and be anonymised (i.e. no particular Tokamak or source code). 1D profiles to include:

- electrons (temperature, density)
- main ions (temperature, density, rotation)
- representative profiles for an example impurity (C, Ne, etc)

The TMC proposed @Mateasek for this task and @jacklovell as the reviewer.

**Comment by Mateasek** [comment]
Is the core and edge supposed to meet on the lcfs? 1D transport codes tend not to connect well with 2D edge simulations along the whole lcfs.

For now I suggest I will inspire myself with some JET profiles and create the model. This will be the easiest and most time efficient for now. Then we can rethink the approach and redo the core model once we have some edge model.

**Comment by mattngc** [comment]
Lets see what happens in #211. Ideally, yes, they should line up... a little bit. It is after all a fake plasma, so you can always do some numerical editing of the profile at the boundary to get them in approximate agreement. The SOLPS guys might even have an AUG shot its based off, in which case you could just look up the shot and be "inspired" by the data.

**Comment by CnlPepper** [comment]
> Is the core and edge supposed to meet on the lcfs? 1D transport codes tend not to connect well with 2D edge simulations along the whole lcfs.

It should matter too much. It doesn't have to be fully consistent as it's just for a demo of the framework. We've blended edge simulations with 1D core simulations using the Blend2D functions to crudely merge the boundary in the past.

**Comment by Mateasek** [comment]
I think this can be closed.
