### ISSUE TITLE
Generomak - first wall specification

### ISSUE THREAD

**Issue by mattngc** [cherab/core#212]
Following issue #209, we need an importable first wall specification. The wall model should be:

- based on an octant or other repeating geometry
- saved with the package as an rsm mesh file
- a low poly first wall outline, simple low poly tiles with an example port or two

The TMC assigned @jacklovell to coordinate this task with @mattngc as reviewer.

**Comment by jacklovell** [comment]
Once we have a limiter polygon from #211 I'll go ahead and make a first wall based on that.

**Comment by Mateasek** [comment]
@jacklovell I talked to one of our mechanical engineers Vojtech Balner, who is now working on PFC and vessel design for COMPASS Upgrade and asked him if he was willing to make components for Generomak. He said he would be happy to contribute, he is a fan of Cherab and likes the pictures produced with it. He predicts that it should not be that much time consuming, since he spent a lot of time with this topic  already and is a CAD engineer. We would not use just scaled PFCs and vessel they do for COMPASS for copyright reasons. We would use his experience and the designs he has as a base to come up with something reasonably shaped and realistic. The point would not be to have shapes which can withstand the plasma, transients and etc., but to look realistic enough in simulations. Please let me know if you agree.

**Comment by jacklovell** [comment]
This would be great, thanks.

**Comment by mattngc** [comment]
> 
> 
> @jacklovell I talked to one of our mechanical engineers Vojtech Balner, who is now working on PFC and vessel design for COMPASS Upgrade and asked him if he was willing to make components for Generomak. He said he would be happy to contribute, he is a fan of Cherab and likes the pictures produced with it. He predicts that it should not be that much time consuming, since he spent a lot of time with this topic already and is a CAD engineer. We would not use just scaled PFCs and vessel they are designing for COMPASS for copyright reasons. We would use his experience and the designs he has as a base to come up with something reasonably shaped and realistic. The point would not be to have shapes which can withstand the plasma, transients and etc., but to look realistic enough in simulations. Please let me know if you agree.

This would be fantastic if you can organise this. Something light weight but realistic. You will probably need to dimension it based on the available plasma edge models since they seem to be a limiting factor.

**Comment by Mateasek** [comment]
> > @jacklovell I talked to one of our mechanical engineers Vojtech Balner, who is now working on PFC and vessel design for COMPASS Upgrade and asked him if he was willing to make components for Generomak. He said he would be happy to contribute, he is a fan of Cherab and likes the pictures produced with it. He predicts that it should not be that much time consuming, since he spent a lot of time with this topic already and is a CAD engineer. We would not use just scaled PFCs and vessel they are designing for COMPASS for copyright reasons. We would use his experience and the designs he has as a base to come up with something reasonably shaped and realistic. The point would not be to have shapes which can withstand the plasma, transients and etc., but to look realistic enough in simulations. Please let me know if you agree.
> 
> This would be fantastic if you can organise this. Something light weight but realistic. You will probably need to dimension it based on the available plasma edge models since they seem to be a limiting factor.

The plan is to derive the PFC tile shapes from the SOLPS mesh. I think that the outer SOLPS mesh contour should be the PFC contour. We will try to minimize the number of tile types and use the mesh instantiating in Raysect. Most of the tiles can be Box primitives (e.g. divertor targets, baffles etc.). This should help us to push down a bit the overall file size. The LFS/HFS limiters should have a bit more complicated shapes to get closer to realistic tiles. The problem might be with ports and the vacuum vessel. They tend to have difficult shapes which then results in larger meshes. We will just start and we will see where it will take us.

**Comment by vsnever** [comment]
@Matesek, you can use a wall outline from this archive, [cherab_generomak.zip](https://github.com/cherab/core/files/4284230/cherab_generomak.zip) in addition to the SOLPS mesh.

**Comment by Mateasek** [comment]
An Update on the PFCs, we have a first version of the PFC contour and of the HFS tiles:
![Progress_day2](https://user-images.githubusercontent.com/969455/99993125-88a96500-2db7-11eb-8a91-b74753e60f73.jpg)

The tiles are all the same, so a single mesh file is needed. The tile is a squared shape with the front surface being a cylindrical shape (usually the shape is a bit more complicated but we thought this would suffice) and the top and bottom edges are cut to make it look nicer. 

The question is if this is sufficient for the HFS or do we want to have guard-limiters on HFS? It would look much better but would increase the space needed to save another mesh. What do you think?

**Comment by vsnever** [comment]
The SOLPS simulations were performed for a DIII-D-like machine. It doesn't have the inner wall guard limiters. I think the simpler the model is, the better.

**Comment by jacklovell** [comment]
This looks great, thanks! I agree with @vsnever, we should keep this as simple as possible. I think what you already have is sufficient for making some nice-looking demo images.

**Comment by mattngc** [comment]
This is fantastic work mate, love where this is going. Will make all our demos so much easier.

**Comment by Mateasek** [comment]
Yesterday Vojtech finished the first version of all the PFC components:
![Generomak_v1__3](https://user-images.githubusercontent.com/969455/100861060-98990700-3491-11eb-99b7-7bd4fd2455a9.jpg)

**Comment by jacklovell** [comment]
This looks brilliant! I'm intrigued by the outboard limiters, which seem to be a long curved shape. Will you be dividing this up into smaller tiles, or providing it as one large mesh?

I wonder whether we should provide STL files in addition to RSM files? That would then allow users to open the meshes in a variety of mesh viewers to help them better understand the objects in the scene. Currently it's not possible to use RSM files with anything other than Raysect. @mattngc what do you think?

**Comment by Mateasek** [comment]
> Will you be dividing this up into smaller tiles, or providing it as one large mesh?

This is actually a good point. It will look much better. I will ask Vojtech to cut it into 4 tiles? 

I don't have a preference about the format, but does stl allow to save vertex normals? I always thought it doesn't. I thought that only obj and rsm supported it. Also, rsm is very efficient to load, it would speed up the demos.

**Comment by vsnever** [comment]
Perfect! I especially like that with such large ports, one can even observe the outer strike point.
>I don't have a preference about the format, but does stl allow to save vertex normals? I always thought it doesn't. I thought that only obj and rsm supported it. Also, rsm is very efficient to load, it would speed up the demos.

The stl format allows to save only facet normal. The vertex normals are used for smoothing, but I'm not sure if this is required here because the surface will have some roughness anyway.

**Comment by jacklovell** [comment]
> I don't have a preference about the format, but does stl allow to save vertex normals? I always thought it doesn't. I thought that only obj and rsm supported it. Also, rsm is very efficient to load, it would speed up the demos.

In that case, how about providing obj and rsm files? I agree with you that we should use rsm for the demos for performance reasons. But we can't assume end users will have rsm files readily available for their devices, so we should provide at least one demo which uses a more widespread format. Even if that demo is just "load the obj files and write out rsm files".

We could even do something like "if rsm files already exist, load them. If not, load obj files and use them, but also write out rsm files for next time the demo is run". This gives you the best of both worlds but would add some additional complexity to the demo.

**Comment by CnlPepper** [comment]
Fantastic, looks great!

Regarding mesh formats, please use (Wavefront) OBJ format. I don't think we should be adding RSM to the repo due to file size. The RSM stores the kdtree with the mesh. It would be better for the users to generate them locally if they want to improve performance between runs.

**Comment by CnlPepper** [comment]
If we have vertex normals, we should keep them, they allow the mesh to be correctly smoothed to form pseudo-curved surfaces. OBJ supports vertex normals.

**Comment by Mateasek** [comment]
I finished the mesh generation. All the meshes saved into obj have 16M.5B, the largest is the outer limiter. The reason is it is the most complicated shape plus it is now several tiles. If this is acceptable, I can write a script which will load the tiles to form the plasma facing components.

**Comment by Mateasek** [comment]
If the outer limiter was a single tile it would probably be much smaller (now it has 12.7 MB). This could allow me to generate a bit finer mesh.

**Comment by mattngc** [comment]
This sort of size sounds ok to me, especially if it means we get a reasonably accurate wall model.

**Comment by Mateasek** [comment]
I used the SOLPS Generomak simulation to see if the tiles will look good in a simulation. Here is the result. I think it is good enough.

![generomak_fw_camera](https://user-images.githubusercontent.com/969455/107707192-c8e6f800-6cc1-11eb-9c68-646acbbfd506.png)

**Comment by vsnever** [comment]
>I used the SOLPS Generomak simulation to see if the tiles will look good in a simulation. Here is the result. I think it is good enough.

Looks really great!

**Comment by jacklovell** [comment]
> I used the SOLPS Generomak simulation to see if the tiles will look good in a simulation. Here is the result. I think it is good enough.
> 
I agree with Vlad: this looks awesome.

**Comment by mattngc** [comment]
> 
> 
> I used the SOLPS Generomak simulation to see if the tiles will look good in a simulation. Here is the result. I think it is good enough.
> 
> ![generomak_fw_camera](https://user-images.githubusercontent.com/969455/107707192-c8e6f800-6cc1-11eb-9c68-646acbbfd506.png)

I agree, this is fantastic. Exactly what Cherab needs to make the documentation and example cases clearer. Big thanks to the COMPASS team for contributing this.

**Comment by Mateasek** [comment]
I think this issue can be closed @jacklovell or @vsnever
