### ISSUE TITLE
Update Cherab's function framework to match Raysect

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#213]
Raysect's function framework has recently been much expanded, and there are now a few things in Cherab which should be updated:

* There is no need to maintain `ConstantxD` classes in Cherab, as Raysect already provides these. 
* The `autowrap_vectorfunctionxd` functions should be updated to wrap `VectorxD` objects as `ConstantVectorxD`, just like Raysect's autowrap functions do with scalars.
* The `ConstantVectorxd` classes in `cherab.core.math.constant` should move to `cherab.core.math.function` (but still be exposed in `cherab.core.math`) They're really part of the function framework, and Cherab already has a `constants` module with actual scientific constants, so this is a recipe for confusion. `cherab.core.math.constant` should be removed.

Whilst I think removing `ConstantxD` implementations from Cherab is worthwhile, do we still want to expose the Raysect `ConstantxD` classes in the `cherab.core.math` namespace? There may be code in the wild which does `from cherab.core.math import Constant1D`, for example. We can fix these instances in all of the Cherab packages, but not necessarily in users' codes.

**Comment by jacklovell** [comment]
@CnlPepper @mattngc thoughts on this? Having just checked through the code, this doesn't require particularly large changes. Most of the changes are just removing `Constant...` boilerplate from examples in the demo scripts and the docs.

**Comment by mattngc** [comment]
Sounds good to me. The intention long term was to expand the math framework on the Raysect side anyway. Cherab should just use the external math libraries provided by Raysect. So I support the above changes.

**Comment by jacklovell** [comment]
Fixed by #214
