### ISSUE TITLE
removing method from a notifier

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#221]
I have discovered one behavior of the notifier class connected to python which I can't find explanation for. I will try to describe it as well as I can.

In a material  __init__() I register a method to a notifier of another class:

``` Python
cdef class LaserMaterial(InhomogeneousVolumeEmitter):

    def __init__(self, Laser laser not None, _NodeBase laser_segment not None, VolumeIntegrator integrator not None):

        super().__init__(laser._integrator)

        self._laser = laser

        self._laser.notifier.add(self._laser_changed)
```

The architecture is similar to the beam. There is a Laser node having some geometry (a list of cylinders). Each cylinder has its own instance of the LaserMaterial with cached affine transforms to the plasma. The caching is done in the _self._laser_changed_ method. The method is added to the laser.notifier to update the cache after certain changes. After different changes, I would like to delete the laser geometry (all the cylinders) and to create a new one. The old geometry is deleted in the laser by:

```python
        # clear geometry to remove segments
        for i in self._geometry:
            self.notifier.remove(i.material._laser_changed)
            i.parent = None
        self._geometry.clear()
```

However, the notifier.remove does not remove the callbacks. It seems that when the callback is added to the notifier using self._laser.notifier.add(self._laser_changed), the _laser_changed is identified as instance of BuiltinMethodType by `isinstance(callback, (MethodType, BuiltinMethodType))` being True, but in the call self.notifier.remove(i.material._laser_changed) it is False. This makes the notifier.remove() actually not to remove the callback. When I define the _laser_changed method to be a cpdef, it fixes this problem. I know this is probably due to my limited python knowledge, but I failed find any reference to this anywhere.

**Comment by CnlPepper** [comment]
How is LaserMaterial._laser_changed defined? If it was a cdef it won't work. A def or cpdef should both work.

You shouldn't need to remove the callbacks, when an object is deleted the weakreference dies and the notifier should auto remove it.

**Comment by Mateasek** [comment]
@CnlPepper   think the [remove method](https://github.com/cherab/core/blob/d58c8c26470209be9643a8c23b9dc9385bbe30e9/cherab/core/utility/notify.py#L71-L76)

```python
    def remove(self, callback):


        if isinstance(callback, MethodType):
            self._remove_method(callback)
        else:
            self._remove_callable(callback)
```
is missing the BuiltinMethodType in the type check to work correctly and in the same way as the add method:

```python
        if isinstance(callback, (MethodType, BuiltinMethodType)):
            self._remove_method(callback)
        else:
            self._remove_callable(callback)
```

Also I think sometimes it is cleaner to remove callbacks (or even necessary) when an object reference is changed. The replaced reference does not have to be deleted if kept by the user for some reason. This might cause problems, to me it caused problems when I was trying to cache transforms, de-parented node's callbacks were still being called and this was causing errors since they were not in the same scenegraph anymore.

**Comment by CnlPepper** [comment]
I'm a little surprised it isn't working as it is. We use cython code in notifiers all the time. Can you answer my query regarding the type of method you were assigning? I'm trying to understand if it is a mistake in usage.

**Comment by CnlPepper** [comment]
Sorry using github on the phone hid the end of the code samples in your message. Can you check the commit that added built-in to add() it may have just been an oversight.

**Comment by CnlPepper** [comment]
It does look like a mistake and it should be present in the remove method too. I'll fix it.

**Comment by Mateasek** [comment]
I have quickly put together an example where I tried to illustrate what I have in mind. The notify_test.pyx file in cherab/tools:

``` cython
from cherab.core.utility import Notifier

cdef class Holder:

    cdef:
        readonly object notifier
        readonly object _hold
    

    def __init__(self, hold=None):
        self.notifier = Notifier()
        self._hold = None
        if hold is not None:
            self.hold = hold

    @property
    def hold(self):
        return self._hold

    @hold.setter
    def hold(self, value):

        if self._hold is not None:
            print("notifier.remove()")
            self.notifier.remove(self._hold.def_print)
            self.notifier.remove(self._hold.cpdef_print)

        self._hold = value
        self.notifier.add(self._hold.def_print)
        self.notifier.add(self._hold.cpdef_print)

cdef class PrintStr:
    cdef:
        public str content
    
    cdef object __weakref__

    def __init__(self, content):
        self.content = content

    def def_print(self):
        print("def_print " + self.content)

    cpdef cpdef_print(self):
        print("cdef_print " + self.content)
```
and the calling script showing what I had in mind. After replacing the object reference, callbacks are not deleted in the notifier.remove call:
``` python
from cherab.tools.notify_test import Holder, PrintStr

stra = PrintStr("a")
strb = PrintStr("b")

holder = Holder()
holder.hold = stra
holder.notifier.add(stra.cpdef_print)
holder.notifier.notify()
print()
print("switch a for b:")
holder.hold = strb
holder.notifier.notify()
```

**Comment by CnlPepper** [comment]
Change made. This class does need a proper unit test at some point. Can you please test it?

**Comment by Mateasek** [comment]
the `isinstance` takes only 2 arguments, you forgot to add parentheses:

```python
if isinstance(callback, (MethodType, BuiltinMethodType)):
````
Also adding the _BuiltinMethodType_ to the [is_present](https://github.com/cherab/core/blob/d58c8c26470209be9643a8c23b9dc9385bbe30e9/cherab/core/utility/notify.py#L80) method causes this error:
```
File "/home/maajk/Python/packages/cherab/cherab_core/cherab/core/utility/notify.py", line 148, in _is_present_method
    if callback.__self__ is instance and callback.__func__ is method:
AttributeError: 'builtin_function_or_method' object has no attribute '__func__'
```

**Comment by CnlPepper** [comment]
Oops, sorry try now.

**Comment by CnlPepper** [comment]
Not sure what to do about the is_present_method issue, but don't have time to look into it now.

**Comment by CnlPepper** [comment]
OK so this has bugged me and I think I can fix it by just checking the __name__ rather than __func__.  Will make the change now.

**Comment by CnlPepper** [comment]
Can you try it again?

**Comment by Mateasek** [comment]
Tried it on the example I posted above and it works. Thanks!

**Comment by Mateasek** [comment]
All the callbacks are correctly being removed now, also when trying to add a callback twice,  it is recognised and not added to the callback list. I think we can close this.
