### ISSUE TITLE
Cherab & Raysect development branches are incompatible

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#222]
Latest versions of Cherab (d58c8c2) and Raysect (7e3573d) development brances are not compatible. When I try to compile cherab, it complains about missing types, e.g. `cherab/tools/equilibrium/efit.pxd:33:17: 'Function2D' is not a type identifier`

I guess it is due to the new function framework being accepted into raysect? Or is there something I missed?

**Comment by CnlPepper** [comment]
Please see the change log in the Raysect development branch. We are reworking the function API. This unfortunately means the imports in cherab will need to be updated.

**Comment by jacklovell** [comment]
This will be fixed in #214. I'll prioritise that over the next couple of days.

**Comment by Mateasek** [comment]
Right, thanks for working on this @jacklovell and @CnlPepper.
