### ISSUE TITLE
Adaptive SART solver

### ISSUE THREAD

**Issue by vsnever** [cherab/core#224]
I was testing the adaptive SART (or SAART) solver, which was used by Juuso Karhunen in [this paper](https://doi.org/10.1063/1.5118885), against the classical SART solver in the problem of tomographic reconstruction of the emission profile in the ITER SOL. Although the adaptive solver does not seem to provide a better solution to my problem compared to SART (or, at least in the case when a smoothing regularisation is applied to the emission profile), now I have the CPU and GPU implementations of SAART (see [this](https://github.com/vsnever/cherab-core/commit/b21041896b5c4835293e6b0cea8396327eed7732)). I can make a pull request if you want the SAART solver in Cherab.

**Comment by jacklovell** [comment]
If there was a noticeable improvement in reconstruction quality with SAART then I think it would be worth including. However, if the result is already similar to SART then it's less clear. We don't want more code to support and maintain unless it provides a capability that cannot be achieved with the existing code.

**Comment by vsnever** [comment]
I'm going to test the SAART solver in the problem of reconstructing a 3D emission profile without smoothing regularization. Unless I get a higher quality reconstruction compared to SART, I think this issue can be closed, at least until someone else asks to add this feature. I'll get back to you with the results.

**Comment by jacklovell** [comment]
OK, great. We can always keep the code around in a separate feature branch for posterity, and if it does become useful in future it'll save somebody else re-implementing it.

**Comment by Mateasek** [comment]
What about keeping such tools in a separate repository instead of the core repository? There might be more tools than inversions in the future.

**Comment by vsnever** [comment]
A test performed on nine different 3D beryllium emission profiles from the ERO2.0 simulations showed that the non-adaptive SART solver is more robust. For four relatively smooth emission profiles, the SAART solver returned the same results as the SART solver, but in fewer iterations. However for the remaining five sharp emission profiles, the SAART solver returned much less accurate results with more iterations than the SART solver.

So, I think this issue can be closed. I'll keep the branch with the SAART solver in my fork in case someone needs it in the future.

**Comment by jacklovell** [comment]
OK, thanks for performing these tests Vlad.
