### ISSUE TITLE
Faulty periodicity check in CylindricalRayTransferEmitter and RayTransferCylinder

### ISSUE THREAD

**Issue by vsnever** [cherab/core#225]
Checking for periodicity in phi-direction during initialisation of CylindricalRayTransferEmitter and RayTransferCylinder may falsely raise an error if the period is non-integer.

I'll make a pull request in a moment.

**Comment by vsnever** [comment]
Here is the PR, #226.

**Comment by jacklovell** [comment]
Fixed by #226.
