### ISSUE TITLE
CI: which version of raysect should we build against?

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#227]
Currently the CI for Cherab development branch and PRs fails because it's trying to pull in Raysect 0.7. This isn't published on PyPI yet, but Cherab requires at least this release for compatibility with the function framework.

To get the build to pass, we could edit .travis.yml to use the Raysect development branch. But Cherab stable should always be compatible with raysect stable. Do we:

1. Manually edit the Travis file to pull released Raysect from PyPI every time we push to master, and then change it back to Raysect development from Github in the next commit on the development branch?
1. Add some logic to the Travis file to somehow detect if we're on master or development, and pull the appropriate Raysect branch from both?
1. Always require Cherab development and master to be compatible with Raysect master (and release 0.7)?
1. Some other solution?

**Comment by CnlPepper** [comment]
Hi Jack,

I see you have been experimenting with the travis configuration. The approach you are taking with the if statement for master vs development is the approach I'd advocate. It also ensures that cherab auto-testing will spot when the raysect development has modified a feature. 

Best regards,
Alex

**Comment by jacklovell** [comment]
OK, I'll pursue this. I haven't managed to get it working for PRs to master yet, but once I do I'll submit a PR to update the development branch.

**Comment by jacklovell** [comment]
Fixed by #229

**Comment by CnlPepper** [comment]
Loks like you'll need to be explict (>=) with the numpy version for the latest release. If you look at the log, the 1.16 version is being used as it is already present in the Travis venv:

![image](https://user-images.githubusercontent.com/8628770/89298739-a4003100-d65d-11ea-928c-236cc55a4db7.png)

**Comment by CnlPepper** [comment]
See line 194 of the log.

**Comment by CnlPepper** [comment]
(for other readers, see the merge request for context).

**Comment by jacklovell** [comment]
Good spot. I thought Travis would spin up a fresh instance for each job, rather than re-using an old instance.

I imagine passing the `--upgrade` option to pip should ensure the newest version of Numpy will be installed over whatever's already there. I'll make another PR to check this.

**Comment by jacklovell** [comment]
Having dug into this further, it looks like Travis does use a fresh venv for each job. The Python 3.6 environment in Travis has Numpy 1.19.0, but the Python 3.7 environment has Numpy 1.16.6. I'd only checked the log for jobs using Python 3.6 (which used 1.19.0 for the "latest" Numpy) and assumed the same packages would be present in 3.7. It's a bit weird that Numpy is present at all in the virtualenv when it's first created, as it's otherwise mostly empty (see e.g. https://travis-ci.com/github/cherab/core/jobs/369343610). Looks like we'll have to install Numpy separately from other packages to manage the versioning properly.

**Comment by jacklovell** [comment]
@CnlPepper thinking a bit more about this, what's the benefit of testing against Numpy 1.16.6? I can see the benefit of testing against the oldest version of Numpy we support (1.15.0 now matplotlib has dropped support for <=1.14) and the latest released version, but why an intermediate version? Could we drop this from the tests, and instead build against more Python versions such as 3.8?

**Comment by CnlPepper** [comment]
@jacklovell we were testing against specific versions of numpy that we know larger users of cherab had installed e.g. UKAEA. It is generally reasonable to test against a few different versions to ensure wide compatibility. I think you should add python 3.8 to the list. I'd only remove environments if the evaluation time becomes a significant issue.

**Comment by CnlPepper** [comment]
> Looks like we'll have to install Numpy separately from other packages to manage the versioning properly.

This isn't necessary, if you specify an explicit numpy version the old version is uninstalled (see the logs for the pip commend results for the older numpy version). Just add numpy>=1.18 to the last numpy environment definition.

**Comment by jacklovell** [comment]
That will only work as long as the version already installed is <1.18. For example, the latest version of Numpy is currently 1.19.1, and the version installed by default in the Py36 environment on travis is 1.19.0. So numpy>=1.18 will already be satisfied, and no upgrade to the latest will be performed.

**Comment by CnlPepper** [comment]
I just spent some time mulling over this and I think we should only test explicit versions, so all "==". We don't want any environments we don't control. Numpy has had bugs in the past and we don't want to chase their bugs while we are developing, which could be the case if the environment starts using a later version. It would be better to explicitly choose to update the latest test version in our test suite when we see there is a need.

**Comment by CnlPepper** [comment]
So perhaps just set the last environment to "numpy==1.19". May be worth switching the $NUMPY variable back to just cover the version number.

**Comment by jacklovell** [comment]
That sounds reasonable. Do we want to do the same thing with the other dependencies: cython, scipy and matplotlib too? I suppose Cherab is probably less exposed to bugs in matplotlib, because it's only needed to avoid `ImportError`s in the unit tests. We did have an issue with a Scipy update breaking the tests a little while ago, but my impression is that we depend less extensively on scipy than Numpy.

And what about Cython?

**Comment by CnlPepper** [comment]
As of recent years, Cython's API is generally quite stable so I've been less inclined to pin a specific version. When 3.0 is release we will probably want to temporarily compile with both 0.29 and 3.0 to check there are no issues. After confidence is built we should remove 0.29 and just stick with the latest.

**Comment by jacklovell** [comment]
I've had another go at this. Specifying `numpy==1.19` still won't give the latest version of Numpy 1.19.x on Python 3.6, because the Travis environment has 1.19.1 on there and 1.19.2 is the latest. It does work on Python 3.7 though, where 1.16.4 is the default (go figure...).

I've modified the travis script now to specify major.minor.revision for Numpy, which guarantees that exact version of Numpy will be used.
