### ISSUE TITLE
Use effective temperature of target species instead of electrons in GaussianLine and MultipletLineShape

### ISSUE THREAD

**Issue by vsnever** [cherab/core#235]
Currently, in `GaussianLine` and `MultipletLineShape` the thermal broadening is calculated using the electron temperature:
```python
te = self.plasma.get_electron_distribution().effective_temperature(point.x, point.y, point.z)
...
 # calculate the line width
sigma = thermal_broadening(self.wavelength, te, self.line.element.atomic_weight)
```
I suggest using the effective temperature of target species instead: 
```python
ts = self.target_species.distribution.effective_temperature(point.x, point.y, point.z)
...
 # calculate the line width
sigma = thermal_broadening(self.wavelength, ts, self.line.element.atomic_weight)
```
For ions, the use of the electron temperature does not cause a large error, but the effective temperature of neutral atoms can be an order of magnitude lower than the electron temperature in far scrape-off layer.

@mattngc, @jacklovell, @Mateasek, If you agree, I'll make this change.

**Comment by Mateasek** [comment]
Definitely fix it, it seems like a serious problem not only for neutrals. Ion and electron temperature difference can be very different in general, it doesn't have to be only for neutrals. There are many factors in play. Nice catch @vsnever

**Comment by Mateasek** [comment]
Should we add some tests for the existing models where possible? It could be done with plasma using the constant plasma slab. The models are important and shouldn't get messed with even by accident.

**Comment by jacklovell** [comment]
Yes, although this should be raised as a separate issue so we can track all the models, not just these two.

**Comment by Mateasek** [comment]
Ok, I will create a separate issue for it.

**Comment by mattngc** [comment]
I'm a bit late to the party on this one, but yes, well spotted Vlad. This is a good change. Happy to see you've PR'd it already.
