### ISSUE TITLE
Installation fails on systems without wheels if Cython is not already installed

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#240]
When installing on systems without a Cherab or Raysect wheel available, or when installing one of the sub-packages such as cherab-solps or cherab-mastu which don't have wheels available for any systems, the installation fails if Cython and numpy are not already installed. An example of where this is relevant is creating a virtual environment for Cherab which is separate from the existing system installation of Python, and then doing `pip install cherab`.

The installation fails because setup.py imports Cython and Numpy before the setuptools setup() function is called which specifies these packages are dependencies. The current workaround is to manually pip install cython and numpy before doing `pip install cherab`, but in reality the latter command should be enough.

The recommended solution is to provide a pyproject.toml file as specified in [PEP 518](https://www.python.org/dev/peps/pep-0518/). This should specify that the build requires setuptools, wheel, cython and numpy.

This issue is most pertinent to the sub-packages without any wheels available, but I think it's good practice to incorporate it into core as well so we have unified setup.py files for all the packages (and any new packages which are developed later and use core for inspiration).

**Comment by CnlPepper** [comment]
I do despise the hodge podge that is python packaging. Looks like a useful file to add. Traditionally people used the requirements.txt file to store these dependencies and were expected to install them manually. The pyproject.toml file looks like a better alternative. Have you tested it?

**Comment by jacklovell** [comment]
I've tested it on cherab-mastu (where I originally ran into the problem) and it seemed to work. I'll make a separate branch in core for you to test: installing from a Github branch will bypass retrieving the wheel anyway which should be sufficient for testing.

**Comment by qingfengxia** [comment]
Similar here on Ubuntu 20.04,  when build wheel


`
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # CONDITIONS OF ANY KIND, either express or implied.
    #
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.
    
    from raysect.core.math.function cimport Function1D, autowrap_function1d
    ^
    ------------------------------------------------------------
    
    cherab/core/math/function/__init__.pxd:19:0: 'raysect/core/math/function/Function1D.pxd' not found
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # CONDITIONS OF ANY KIND, either express or implied.
    #
    # See the Licence for the specific language governing permissions and limitations
    # under the Licence.
    
    from raysect.core.math.function cimport Function1D, autowrap_function1d
    ^
    ------------------------------------------------------------
    
    cherab/core/math/function/__init__.pxd:19:0: 'raysect/core/math/function/autowrap_function1d.pxd' not found

`

**Comment by qingfengxia** [comment]
I have been working on pxd search path, but later find,   there is a missing file.  it that due to  raysect refactored and remove some file?

ls /usr/local/lib/python3.8/dist-packages/raysect/core/math/function/
base.cpython-38-x86_64-linux-gnu.so  base.pxd  base.pyx  float  __init__.pxd  __init__.py  __pycache__  vector3d

**Comment by qingfengxia** [comment]
this is another issue, so moved to new issue

**Comment by CnlPepper** [comment]
@jacklovell sorry I never got around to testing this. I'm happy for the toml file to be added if you have found it works. The pep is quite clear.
