### ISSUE TITLE
Fix incorrect inheritance of TotalRadiatedPower from _RadiatedPower class

### ISSUE THREAD

**Issue by vsnever** [cherab/core#247]
The `TotalRadiatedPower` class in `core.atomic.rates` describes the total radiated power in equilibrium conditions, which is unresolved on ionisation state. Therefore, this class must not inherit from ionisation-resolved `_RadiatedPower` class. Otherwise, the `AtomicData.total_radiated_power()` interface is broken. This should be fixed before cherab/adas#3.

**Comment by mattngc** [comment]
Resolved by @vsnever in PR #248.
