### ISSUE TITLE
cherab not compatible with raysect 0.7 (please update requirements.txt)

### ISSUE THREAD

**Issue by qingfengxia** [cherab/core#249]
Similar here on Ubuntu 20.04, when build wheel

```
Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function cimport Function1D, autowrap_function1d
^
------------------------------------------------------------

cherab/core/math/function/__init__.pxd:19:0: 'raysect/core/math/function/Function1D.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function cimport Function1D, autowrap_function1d
^
------------------------------------------------------------

cherab/core/math/function/__init__.pxd:19:0: 'raysect/core/math/function/autowrap_function1d.pxd' not found
```

**Comment by qingfengxia** [comment]
by fix the raysect   version to 0.6.1  in   requirements.txt,  it may work

**Comment by jacklovell** [comment]
The released version of Cherab requires raysect 0.6: https://github.com/cherab/core/blob/d58c8c26470209be9643a8c23b9dc9385bbe30e9/setup.py#L100

If you have installed raysect 0.7 separately, you should uninstall it and reinstall 0.6.Running `pip install cherab` should do this automatically.

We will soon be releasing a Cherab update which requires 0.7.

**Comment by vsnever** [comment]
@jacklovell, but this is inconsistent with requirements.txt:
cython>=0.28
numpy
scipy
matplotlib
**raysect>=0.6.0**

I'm not sure, but if the package is installed via pip it might use requirements.txt rather than install_requires from setup.py.

**Comment by qingfengxia** [comment]
interesting, I got stuck  for a quarter when build raysect
  Building wheel for raysect (setup.py) ... |
