### ISSUE TITLE
Add the __eq__, __ne__ and __hash__ methods to the Line class

### ISSUE THREAD

**Issue by vsnever** [cherab/core#255]
I'm adding the interfaces to the ADAS603 routines in the cherab.adas module, and I would like to be able to create dictionaries with `Line` instances both as keys and values. Of course, I can always have dictionaries with tuples (Element, charge, transition), but `Line` instances seem to be more appropriate. So, is it worth adding the `__eq__`, `__ne__` and `__hash__` methods to the `Line` class, or is it better to leave it as it is and use tuples in dictionaries instead?

**Comment by CnlPepper** [comment]
I see no downside to implementing the ability to hash and check equality. It would be cleaner to use Line objects that tuples. This would need to hash and equality support for the Element classes too. The hash function can simply return a tuple for both Element and Line, constructed form the internal state.

**Comment by vsnever** [comment]
The users should use only pre-initialised instances of `Element` classes instead of creating their own, so the support for hash and equality is not absolutely necessary for `Element` classes, but I'll implement them in `Element`/`Isotope` for consistency.

**Comment by vsnever** [comment]
Fixed in #246.
