### ISSUE TITLE
Add Vector blending functions

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#260]
As was discussed in #254, vector blending functions should be added. Currently there are only methods for blending of scalar functions (BlendxD). 

Raysect is equipped with two Vector3D interpolations [lerp](https://github.com/raysect/source/blob/6aa8b60f2877635d3e58ac7636ef58f069796f72/raysect/core/math/vector.pyx#L469) and [slerp](https://github.com/raysect/source/blob/6aa8b60f2877635d3e58ac7636ef58f069796f72/raysect/core/math/vector.pyx#L497) which can be used by blending function. I think there are few questions how to implement this.

1. Because now only Vector3D class has interpolation, only BlendVector3D can be done. Should I raise an issue at Raysect github to add Vector2D interpolations?
2. Should the current BlendxD functions be renamed to BlendScalarxD? It would fit better with the current naming convention, but it would break backwards compatibility. This could be solved by having BlendxD classes inheriting BlendScalarxD
3. Should there be one or two separate classes for blending with lerp and slerp? I think having one class with the possibility to switch between lerp and slerp would be better.

Could I ask @CnlPepper to suggest the best way how to add this feature before I start? Thanks

**Comment by CnlPepper** [comment]
Hi @Mateasek. I started a re-implementation of the blend functions in Raysect. The functions are currently missing tests and docs, but should be functional. I'l finish them off when I get a moment. It would be best to replace the cherab functions with these. There are both float and vector3d versions. See:

https://github.com/raysect/source/tree/feature/blendfn

**Comment by CnlPepper** [comment]
We don't have any Vector2D functions implemented, they are not often used. Vector3D is generally used everywhere.

**Comment by CnlPepper** [comment]
I've merged the relevant functions into the raysect development branch.
