### ISSUE TITLE
Issues with installation in Ubuntu 18.04.5 

### ISSUE THREAD

**Issue by EdmundBenedict** [cherab/core#261]
I have been having issues with installing Cherab on my Ubuntu machine, pip throws no errors when I install:

Collecting cherab
  Downloading https://files.pythonhosted.org/packages/06/c3/99d1b90e072505cb7b4e8c00426edd30d362a735358714d2375753f0ab37/cherab-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (30.8MB)
    100% |████████████████████████████████| 30.8MB 49kB/s 
Collecting raysect==0.6.0 (from cherab)
  Downloading https://files.pythonhosted.org/packages/a8/b5/12fe902bfb69cf6231e0e724482766dcde26f13a538bbad186981debc801/raysect-0.6.0-cp36-cp36m-manylinux1_x86_64.whl (39.3MB)
    100% |████████████████████████████████| 39.3MB 34kB/s 
Requirement already satisfied: matplotlib in ./.local/lib/python3.6/site-packages (from cherab)
Requirement already satisfied: numpy in ./.local/lib/python3.6/site-packages (from cherab)
Requirement already satisfied: scipy in ./.local/lib/python3.6/site-packages (from cherab)
Requirement already satisfied: cython>=0.28 in ./.local/lib/python3.6/site-packages (from cherab)
Requirement already satisfied: python-dateutil>=2.1 in ./.local/lib/python3.6/site-packages (from matplotlib->cherab)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.6/site-packages (from matplotlib->cherab)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.6/site-packages (from matplotlib->cherab)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.6/site-packages (from matplotlib->cherab)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./.local/lib/python3.6/site-packages (from matplotlib->cherab)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.6/site-packages (from python-dateutil>=2.1->matplotlib->cherab)
Installing collected packages: raysect, cherab
  Found existing installation: raysect 0.7.0
    Uninstalling raysect-0.7.0:
      Successfully uninstalled raysect-0.7.0
Successfully installed cherab-1.2.0 raysect-0.6.0

But when I try to download the required data files from the OpenADAS web archive, it repeatedly throws an error:

In [2]: from cherab.openadas.repository import populate                                  
In [3]: populate()          

Installing adf11/scd12/scd12_h.dat...
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-3-b01bf44e487f> in <module>
----> 1 populate()

/usr/local/lib/python3.6/dist-packages/cherab/openadas/repository/create.py in populate(download, repository_path, adas_path)
    380     }
    381 
--> 382     install_files(rates, download=download, repository_path=repository_path, adas_path=adas_path)
    383     repository.update_wavelengths(wavelengths, repository_path=repository_path)

/usr/local/lib/python3.6/dist-packages/cherab/openadas/install.py in install_files(configuration, download, repository_path, adas_path)
     36         if adf.lower() == 'adf11scd':
     37             for args in configuration[adf]:
---> 38                 install_adf11scd(*args, download=download, repository_path=repository_path, adas_path=adas_path)
     39         if adf.lower() == 'adf11acd':
     40             for args in configuration[adf]:

/usr/local/lib/python3.6/dist-packages/cherab/openadas/install.py in install_adf11scd(element, file_path, download, repository_path, adas_path)
     92     rate_cherab = _notation_adf11_adas2cherab(rate_adas, "scd")  # convert from adas to cherab notation
     93 
---> 94     repository.update_ionisation_rates(rate_cherab, repository_path)
     95 
     96 

/usr/local/lib/python3.6/dist-packages/cherab/openadas/repository/atomic.py in update_ionisation_rates(rates, repository_path)
     65         path = os.path.join(repository_path, 'ionisation/{}.json'.format(species.symbol.lower()))
     66 
---> 67         _update_and_write_adf11(species, rate_data, path)
     68 
     69 

/usr/local/lib/python3.6/dist-packages/cherab/openadas/repository/atomic.py in _update_and_write_adf11(species, rate_data, path)
    163         try:
    164             with open(path, 'r') as f:
--> 165                 content = RecursiveDict.from_dict(json.load(f))
    166         except FileNotFoundError:
    167             content = RecursiveDict()

/usr/lib/python3.6/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    297         cls=cls, object_hook=object_hook,
    298         parse_float=parse_float, parse_int=parse_int,
--> 299         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    300 
    301 

/usr/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/usr/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    353         """
    354         try:
--> 355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
    357             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)

I am not sure if this is a bug or just some mistake I have made in the installation, but I have been unable to figure out what the issue might be after reinstalling it as well as any associated packages multiple times

**Comment by vsnever** [comment]
Hi @EdmundBenedict, thanks for reporting this.
Have you ever installed a previous version of Cherab on this machine? 
Could you please delete the folder `~/.cherab/openadas/repository` and then run `populate()` again?

This bug reminds me #243, which is already fixed in the development branch.

**Comment by EdmundBenedict** [comment]
Ah yes, that seems to have fixed the issue, thank you so much! 
I am sorry to continue to bother you, but one other issue is in running the example calculation for the fractional abundances (https://cherab.github.io/documentation/demonstrations/atomic_data/fractional_abundance.html#fractional-abundances) I have the issue:

In [1]: import matplotlib.pyplot as plt                                                  

In [2]: plt.ion()                                                                        

In [3]: from cherab.core.atomic import neon                                              

In [4]: from cherab.adas import ADAS                                                     
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-6e4135e0c8ff> in <module>
----> 1 from cherab.adas import ADAS

ModuleNotFoundError: No module named 'cherab.adas'

Has this module changed name? Or do I need to install it separately?

**Comment by EdmundBenedict** [comment]
Sorry, I see now that I need cherab-adas installed for this, sorry again for bothering you

**Comment by vsnever** [comment]
> 
> 
> Sorry, I see now that I need cherab-adas installed for this, sorry again for bothering you

No problem. You also need the full ADAS package locally installed on your machine to run this. Try `demos/openadas/frac_abundance.py` instead.

**Comment by EdmundBenedict** [comment]
Thank you very much, that was exactly what I needed!
Also, sorry I didn't see your question above, I did not have a previous version of Cherab on my machine, but I did have some issues with the installation, so it was not my first install. Although these issues appeared the first time I called "populate()" so I don't know how that directory was filled
