### ISSUE TITLE
Possible issue with populate() function for OpenADAS

### ISSUE THREAD

**Issue by EdmundBenedict** [cherab/core#263]
Hi, I have recently installed Cherab, but have found that when using the Line() function, only a restricted set of transitions were available. I checked the .cherab/openadas/repository/ folder and found that a number of files for different ionisation stages were missing. For example, the wavelength folder for carbon only contains 0.json,1.json, 2.json, 5.json but not 3.json or 4.json, and the files that are there start at ~300nm, with none of the lower transitions available on open.adas.ac.uk. 
Is this correct? Thank you.

**Comment by vsnever** [comment]
Hi @EdmundBenedict,
The `populate()` function parses only selected data from OpenADAS. You can install additional data manually. For example, for C<sup>3+</sup> and C<sup>4+</sup>, do:
```python
from cherab.core.atomic.elements import carbon
from cherab.openadas.install import install_adf15
install_adf15(carbon, 3, 'adf15/pec96#c/pec96#c_pju#c3.dat', download=True)
install_adf15(carbon, 4, 'adf15/pec96#c/pec96#c_pju#c4.dat', download=True)
```
This will update both the PEC and wavelength repositories.

Please note, that the PEC93 and PEC40 formats are currently not supported (issue #256) as well as the metastable-resolved PECs (issue #257). Also, be aware of the issue #258.

**Comment by EdmundBenedict** [comment]
Great, thank you!

**Comment by EdmundBenedict** [comment]
Hi, just wanted to ask further if there were other formats currently not supported? I have been trying to populate the data for iron like those of the other atoms included, but I repeatedly get the error:
JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)

I have tried this two ways, by directly calling the "install_" functions (shown here for the SCD files):

from cherab.core.atomic.elements import iron
from cherab.openadas.install import install_adf11scd,install_adf11acd,install_adf11ccd,install_adf11plt,install_adf11prb,install_adf11prc

import os
import urllib

from cherab.openadas import repository
from cherab.openadas.parse import *
from cherab.core.utility import RecursiveDict, PerCm3ToPerM3, Cm3ToM3

install_adf11scd(iron,'adf11/scd74/scd74_fe.dat', download=True, repository_path=None, adas_path=None)
install_adf11scd(iron,'adf11/scd85/scd85_fe.dat', download=True, repository_path=None, adas_path=None)
install_adf11scd(iron,"adf11/scd92/scd92_fe.dat", download=True, repository_path=None, adas_path=None)
install_adf11scd(iron,'adf11/scd93/scd93_fe.dat', download=True, repository_path=None, adas_path=None)
install_adf11scd(iron,'adf11/scd89/scd89_fe.dat', download=True, repository_path=None, adas_path=None)


And I have also tried to follow the populate() function structure:
import os
import urllib
from cherab.openadas import repository
from cherab.openadas.parse import *
from cherab.core.utility import RecursiveDict, PerCm3ToPerM3, Cm3ToM3

**Comment by vsnever** [comment]
This is caused by the same bug, #243, which is already fixed in the development branch. I tried:
```python
from cherab.core.atomic.elements import iron
from cherab.openadas.install import install_adf11scd,install_adf11acd,install_adf11ccd,install_adf11plt,install_adf11prb,install_adf11prc
install_adf11scd(iron,'adf11/scd74/scd74_fe.dat', download=True, repository_path=None, adas_path=None)
install_adf11scd(iron,'adf11/scd85/scd85_fe.dat', download=True, repository_path=None, adas_path=None)
install_adf11scd(iron,"adf11/scd92/scd92_fe.dat", download=True, repository_path=None, adas_path=None)
install_adf11scd(iron,'adf11/scd93/scd93_fe.dat', download=True, repository_path=None, adas_path=None)
install_adf11scd(iron,'adf11/scd89/scd89_fe.dat', download=True, repository_path=None, adas_path=None)
```
with the development version of Cherab, and got no errors. Until the new version of Cherab is released, the only solution for you is to switch to the development version of Cherab:
```
git clone https://github.com/cherab/core.git cherab-core
cd cherab-core
git checkout development
git pull
python setup.py install --user
```

**Comment by EdmundBenedict** [comment]
Do I need to change raysect to the development branch too? I've been getting the "X is not a type identifier" errors, which I see came up before in a previous issue.
Thank you for all your help.

**Comment by vsnever** [comment]
Strange, I thought that the Cherab development branch works fine with the Raysect v 0.7. But yes, if you have these kind of errors, try switching Raysect to the development branch as well.

**Comment by EdmundBenedict** [comment]
Yeah, when I switched to the raysect development branch it compiled fine, and now the install_adf11scd functions work too, thanks!

**Comment by jacklovell** [comment]
Raysect 0.6 and 0.7 are incompatible. Cherab stable requires raysect 0.6, whereas development requires 0.7. If you'd previously installed cherab stable through pip it would have pulled in raysect 0.6 as a dependency. That dependency isn't automatically updated when you checkout cherab development and install it with setup.py.
