### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#266]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

_Originally posted by @CnlPepper in https://github.com/cherab/core/issues/262#issuecomment-778169307_

Putting this in a new issue so it doesn't get lost in #262

**Comment by StanczakDominik** [comment]
Heyo! I've done some CI work at https://github.com/PlasmaPy/PlasmaPy/ and your current travis.yml script looks pretty simple; I could probably handle transitioning that to github actions if you'd like. As a first-time contributor I'd need a sign off on the PR ( https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/ ) for the checks to actually run.

Also, this is a really dang cool package you've got here! 😄
