### ISSUE TITLE
Install issue: error compiling Cython files

### ISSUE THREAD

**Issue by chrismarsden7** [cherab/core#305]
Hi,

I have successfully cloned and setup (in develop mode) Raysect, and have ran a test case (just to check it has actually installed correctly). I have then cloned Cherab and also ran setup.py develop, and keep getting this issue:

> my_env) chris@chris:~/git_repos/cherab_repo/core$ python --version
> Python 3.8.10
> (my_env) chris@chris:~/git_repos/cherab_repo/core$ which python
> /home/chris/anaconda3/envs/my_env/bin/python
> (my_env) chris@chris:~/git_repos/cherab_repo/core$ cython --version
> Cython version 0.29.21
> (my_env) chris@chris:~/git_repos/cherab_repo/core$ which cython
> /home/chris/anaconda3/envs/my_env/bin/cython
> (my_env) chris@chris:~/git_repos/cherab_repo/core$ python setup.py develop
> Compiling cherab/openadas/rates/pec.pyx because it changed.
> Compiling cherab/openadas/rates/atomic.pyx because it changed.
> Compiling cherab/openadas/rates/beam.pyx because it changed.
> Compiling cherab/openadas/rates/cx.pyx because it changed.
> Compiling cherab/openadas/rates/radiated_power.pyx because it changed.
> Compiling cherab/core/species.pyx because it changed.
> Compiling cherab/core/distribution.pyx because it changed.
> Compiling cherab/core/model/lineshape.pyx because it changed.
> Compiling cherab/core/model/plasma/bremsstrahlung.pyx because it changed.
> Compiling cherab/core/model/plasma/recombination.pyx because it changed.
> Compiling cherab/core/model/plasma/impact_excitation.pyx because it changed.
> Compiling cherab/core/model/plasma/total_radiated_power.pyx because it changed.
> Compiling cherab/core/model/attenuator/singleray.pyx because it changed.
> Compiling cherab/core/model/beam/charge_exchange.pyx because it changed.
> Compiling cherab/core/model/beam/beam_emission.pyx because it changed.
> Compiling cherab/core/plasma/model.pyx because it changed.
> Compiling cherab/core/plasma/material.pyx because it changed.
> Compiling cherab/core/plasma/node.pyx because it changed.
> Compiling cherab/core/math/blend.pyx because it changed.
> Compiling cherab/core/math/constant.pyx because it changed.
> Compiling cherab/core/math/mappers.pyx because it changed.
> Compiling cherab/core/math/samplers.pyx because it changed.
> Compiling cherab/core/math/slice.pyx because it changed.
> Compiling cherab/core/math/clamp.pyx because it changed.
> Compiling cherab/core/math/mask.pyx because it changed.
> Compiling cherab/core/math/caching/caching1d.pyx because it changed.
> Compiling cherab/core/math/caching/caching2d.pyx because it changed.
> Compiling cherab/core/math/caching/caching3d.pyx because it changed.
> Compiling cherab/core/math/interpolators/interpolators3d.pyx because it changed.
> Compiling cherab/core/math/interpolators/interpolators2d.pyx because it changed.
> Compiling cherab/core/math/interpolators/interpolators1d.pyx because it changed.
> Compiling cherab/core/math/function/vectorfunction3d.pyx because it changed.
> Compiling cherab/core/math/function/vectorfunction2d.pyx because it changed.
> Compiling cherab/core/beam/model.pyx because it changed.
> Compiling cherab/core/beam/material.pyx because it changed.
> Compiling cherab/core/beam/node.pyx because it changed.
> Compiling cherab/tools/plasmas/slab.pyx because it changed.
> Compiling cherab/tools/plasmas/gaussian_volume.pyx because it changed.
> Compiling cherab/tools/inversions/voxels.pyx because it changed.
> Compiling cherab/tools/emitters/radiation_function.pyx because it changed.
> Compiling cherab/tools/equilibrium/efit.pyx because it changed.
> [ 1/41] Cythonizing cherab/core/beam/material.pyx
> [ 2/41] Cythonizing cherab/core/beam/model.pyx
> [ 3/41] Cythonizing cherab/core/beam/node.pyx
> [ 4/41] Cythonizing cherab/core/distribution.pyx
> [ 5/41] Cythonizing cherab/core/math/blend.pyx
> [ 6/41] Cythonizing cherab/core/math/caching/caching1d.pyx
> [ 7/41] Cythonizing cherab/core/math/caching/caching2d.pyx
> [ 8/41] Cythonizing cherab/core/math/caching/caching3d.pyx
> [ 9/41] Cythonizing cherab/core/math/clamp.pyx
> [10/41] Cythonizing cherab/core/math/constant.pyx
> [11/41] Cythonizing cherab/core/math/function/vectorfunction2d.pyx
> [12/41] Cythonizing cherab/core/math/function/vectorfunction3d.pyx
> [13/41] Cythonizing cherab/core/math/interpolators/interpolators1d.pyx
> [14/41] Cythonizing cherab/core/math/interpolators/interpolators2d.pyx
> [15/41] Cythonizing cherab/core/math/interpolators/interpolators3d.pyx
> [16/41] Cythonizing cherab/core/math/mappers.pyx
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> #
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.vector cimport Vector3D
> from raysect.core.math.function cimport Function3D
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/vectorfunction3d.pxd:20:0: 'raysect/core/math/function/Function3D.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> cdef VectorFunction3D autowrap_vectorfunction3d(object function)
> 
> 
> cdef class ScalarToVectorFunction3D(VectorFunction3D):
> 
>     cdef Function3D _x, _y, _z
>         ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/vectorfunction3d.pxd:38:9: 'Function3D' is not a type identifier
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> 
> from raysect.core.math.vector cimport new_vector3d, Vector3D
> from raysect.core.math.function cimport autowrap_function3d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/vectorfunction3d.pyx:23:0: 'raysect/core/math/function/autowrap_function3d.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> # CONDITIONS OF ANY KIND, either express or implied.
> #
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/__init__.pxd:19:0: 'raysect/core/math/function/Function1D.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> # CONDITIONS OF ANY KIND, either express or implied.
> #
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/__init__.pxd:19:0: 'raysect/core/math/function/autowrap_function1d.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> #
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> from raysect.core.math.function cimport Function2D, autowrap_function2d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/__init__.pxd:20:0: 'raysect/core/math/function/Function2D.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> #
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> from raysect.core.math.function cimport Function2D, autowrap_function2d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/__init__.pxd:20:0: 'raysect/core/math/function/autowrap_function2d.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> from raysect.core.math.function cimport Function2D, autowrap_function2d
> from raysect.core.math.function cimport Function3D, autowrap_function3d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/__init__.pxd:21:0: 'raysect/core/math/function/Function3D.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> from raysect.core.math.function cimport Function2D, autowrap_function2d
> from raysect.core.math.function cimport Function3D, autowrap_function3d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/__init__.pxd:21:0: 'raysect/core/math/function/autowrap_function3d.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> cdef VectorFunction2D autowrap_vectorfunction2d(object function)
> 
> 
> cdef class ScalarToVectorFunction2D(VectorFunction2D):
> 
>     cdef Function2D _x, _y, _z
>         ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/vectorfunction2d.pxd:38:9: 'Function2D' is not a type identifier
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> # CONDITIONS OF ANY KIND, either express or implied.
> #
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/__init__.pxd:19:0: 'raysect/core/math/function/Function1D.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> # CONDITIONS OF ANY KIND, either express or implied.
> #
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> ^
> ------------------------------------------------------------
> 
> cherab/core/math/function/__init__.pxd:19:0: 'raysect/core/math/function/autowrap_function1d.pxd' not found
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> #
> # See the Licence for the specific language governing permissions and limitations
> # under the Licence.
> 
> from raysect.core.math.function cimport Function1D, autowrap_function1d
> from raysect.core.math.function cimport Function2D, autowrap_function2d
> ^

I am using a Conda environment with all of the listed prerequisites installed. I also get the exact same error regardless of whether or not I am install Raysect and/or Cherab with pip.

Cheers,
Chris

**Comment by chrismarsden7** [comment]
Edit: I am unsure why my copy paste of my terminal output is so strangely formatted. However, it should all still be there.

**Comment by vsnever** [comment]
Hi chrismarsden7,

It looks like a version mismatch. Are you installing both Raysect and Cherab from the master branches? If so, they are incompatible since the latest stable version of Cherab requires Raysect 0.6.0 and the latest stable version of Raysect is 0.7.0.

Instead of downgrading to Raysect 0.6.0, I recommend installing Cherab from the development branch because it's compatible with Raysect 0.7.0.
```bash
git checkout development
git pull
python setup.py develop --user
```

**Comment by chrismarsden7** [comment]
> Hi @chrismarsden7,
> 
> It looks like a version mismatch. Are you installing both Raysect and Cherab from the master branches? If so, they are incompatible since the latest stable version of Cherab requires Raysect 0.6.0 and the latest stable version of Raysect is 0.7.0.
> 
> Instead of downgrading to Raysect 0.6.0, I recommend installing Cherab from the development branch because it's compatible with Raysect 0.7.0.
> 
> ```shell
> git checkout development
> git pull
> python setup.py develop --user
> ```

Hi vsnever, my apologies for the late reply. I have performed a fresh clone of the cherab development branch, and have a different error now:

`(my_env) chris@chris:~/git_repos/cherab_repo/core$ python setup.py develop --user
Compiling cherab/openadas/rates/pec.pyx because it changed.
Compiling cherab/openadas/rates/atomic.pyx because it changed.
Compiling cherab/openadas/rates/beam.pyx because it changed.
Compiling cherab/openadas/rates/cx.pyx because it changed.
Compiling cherab/openadas/rates/radiated_power.pyx because it changed.
Compiling cherab/core/species.pyx because it changed.
Compiling cherab/core/distribution.pyx because it changed.
Compiling cherab/core/utility/constants.pyx because it changed.
Compiling cherab/core/model/lineshape.pyx because it changed.
Compiling cherab/core/model/plasma/bremsstrahlung.pyx because it changed.
Compiling cherab/core/model/plasma/recombination.pyx because it changed.
Compiling cherab/core/model/plasma/impact_excitation.pyx because it changed.
Compiling cherab/core/model/plasma/total_radiated_power.pyx because it changed.
Compiling cherab/core/model/attenuator/singleray.pyx because it changed.
Compiling cherab/core/model/beam/charge_exchange.pyx because it changed.
Compiling cherab/core/model/beam/beam_emission.pyx because it changed.
Compiling cherab/core/plasma/model.pyx because it changed.
Compiling cherab/core/plasma/material.pyx because it changed.
Compiling cherab/core/plasma/node.pyx because it changed.
Compiling cherab/core/atomic/line.pyx because it changed.
Compiling cherab/core/atomic/interface.pyx because it changed.
Compiling cherab/core/atomic/elements.pyx because it changed.
Compiling cherab/core/atomic/rates.pyx because it changed.
Compiling cherab/core/math/mappers.pyx because it changed.
Compiling cherab/core/math/samplers.pyx because it changed.
Compiling cherab/core/math/slice.pyx because it changed.
Compiling cherab/core/math/clamp.pyx because it changed.
Compiling cherab/core/math/mask.pyx because it changed.
Compiling cherab/core/math/caching/caching1d.pyx because it changed.
Compiling cherab/core/math/caching/caching2d.pyx because it changed.
Compiling cherab/core/math/caching/caching3d.pyx because it changed.
Compiling cherab/core/math/interpolators/utility.pyx because it changed.
Compiling cherab/core/math/interpolators/interpolators3d.pyx because it changed.
Compiling cherab/core/math/interpolators/interpolators2d.pyx because it changed.
Compiling cherab/core/math/interpolators/interpolators1d.pyx because it changed.
Compiling cherab/core/beam/model.pyx because it changed.
Compiling cherab/core/beam/material.pyx because it changed.
Compiling cherab/core/beam/node.pyx because it changed.
Compiling cherab/tools/raytransfer/roughconductor.pyx because it changed.
Compiling cherab/tools/raytransfer/emitters.pyx because it changed.
Compiling cherab/tools/plasmas/slab.pyx because it changed.
Compiling cherab/tools/plasmas/gaussian_volume.pyx because it changed.
Compiling cherab/tools/primitives/axisymmetric_mesh.pyx because it changed.
Compiling cherab/tools/inversions/voxels.pyx because it changed.
Compiling cherab/tools/inversions/sart.pyx because it changed.
Compiling cherab/tools/emitters/radiation_function.pyx because it changed.
Compiling cherab/tools/equilibrium/efit.pyx because it changed.
[ 1/47] Cythonizing cherab/core/atomic/elements.pyx
[ 2/47] Cythonizing cherab/core/atomic/interface.pyx
[ 3/47] Cythonizing cherab/core/atomic/line.pyx
[ 4/47] Cythonizing cherab/core/atomic/rates.pyx
[ 5/47] Cythonizing cherab/core/beam/material.pyx
[ 6/47] Cythonizing cherab/core/beam/model.pyx
[ 7/47] Cythonizing cherab/core/beam/node.pyx
[ 8/47] Cythonizing cherab/core/distribution.pyx
[ 9/47] Cythonizing cherab/core/math/caching/caching1d.pyx
[10/47] Cythonizing cherab/core/math/caching/caching2d.pyx
[11/47] Cythonizing cherab/core/math/caching/caching3d.pyx
[12/47] Cythonizing cherab/core/math/clamp.pyx
[13/47] Cythonizing cherab/core/math/interpolators/interpolators1d.pyx
[14/47] Cythonizing cherab/core/math/interpolators/interpolators2d.pyx
[15/47] Cythonizing cherab/core/math/interpolators/interpolators3d.pyx
[16/47] Cythonizing cherab/core/math/interpolators/utility.pyx
[17/47] Cythonizing cherab/core/math/mappers.pyx
[18/47] Cythonizing cherab/core/math/mask.pyx
[19/47] Cythonizing cherab/core/math/samplers.pyx
[20/47] Cythonizing cherab/core/math/slice.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function.float cimport Blend1D, Blend2D, Blend3D
^
------------------------------------------------------------

cherab/core/math/__init__.pxd:19:0: 'raysect/core/math/function/float/Blend1D.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function.float cimport Blend1D, Blend2D, Blend3D
^
------------------------------------------------------------

cherab/core/math/__init__.pxd:19:0: 'raysect/core/math/function/float/Blend2D.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function.float cimport Blend1D, Blend2D, Blend3D
^
------------------------------------------------------------

cherab/core/math/__init__.pxd:19:0: 'raysect/core/math/function/float/Blend3D.pxd' not found
[21/47] Cythonizing cherab/core/model/attenuator/singleray.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function.float cimport Blend1D, Blend2D, Blend3D
^
------------------------------------------------------------

cherab/core/math/__init__.pxd:19:0: 'raysect/core/math/function/float/Blend1D.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function.float cimport Blend1D, Blend2D, Blend3D
^
------------------------------------------------------------

cherab/core/math/__init__.pxd:19:0: 'raysect/core/math/function/float/Blend2D.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function.float cimport Blend1D, Blend2D, Blend3D
^
------------------------------------------------------------

cherab/core/math/__init__.pxd:19:0: 'raysect/core/math/function/float/Blend3D.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the Licence for the specific language governing permissions and limitations
# under the Licence.

from raysect.core.math.function.float cimport Blend1D, Blend2D, Blend3D
^
------------------------------------------------------------

cherab/core/math/__init__.pxd:19:0: 'raysect/core/math/function/float/Blend1D.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
`

**Comment by vsnever** [comment]
Could you please check which version of Raysect you have installed?
```
pip show raysect
```
or
```
import raysect
raysect.__version__
``` 
Such errors occur if the version is 0.6.1 or earlier.

**Comment by chrismarsden7** [comment]
Raysect is version 0.7.0. This is for the pip installed raysect. I also have a copy of raysect that I cloned from the repo just last week that presumably is also newer than 0.6.1

**Comment by jacklovell** [comment]
> Edit: I am unsure why my copy paste of my terminal output is so strangely formatted. However, it should all still be there.

Put the terminal output inside a pair of triple backticks, and it'll include it verbatim. Otherwise you're getting markdown formatting (e.g. every `#` in your terminal output translates to "large heading font for the rest of this line".

See https://guides.github.com/features/mastering-markdown/

Back on topic, I agree with @vsnever: you should use the development branch of raysect if you're using the development branch of Cherab. We only guarantee compatibility between raysect releases and the master branch of Cherab.

**Comment by vsnever** [comment]
I see, blend functions were added in Raysect 0.7.1, which is not yet released. However, the development brunch of Cherab requires Raysect 0.7.0. We need to change it to 0.7.1, otherwise Raysect will be automatically downgraded to 0.7.0 after the Cherab installation is complete.

**Comment by vsnever** [comment]
@chrismarsden7, please wait for #306 to be merged. After that, you'll need to reinstall Raysect and Cherab from development branches.

**Comment by chrismarsden7** [comment]
Hi again, I did a clean clone and install of the development branches of both raysect and cherab, and had no issues (I can import both), though as you said, it did downgrade raysect back to 0.7.0 from 0.7.1. Will this be a problem, or is it safe for me to continue now in using these packages?

**Comment by vsnever** [comment]
> Hi again, I did a clean clone and install of the development branches of both raysect and cherab, and had no issues (I can import both), though as you said, it did downgrade raysect back to 0.7.0 from 0.7.1. Will this be a problem, or is it safe for me to continue now in using these packages?

You should reinstall Raysect again, otherwise the latest features that require Raysect 0.7.1 will not work. Fortunately, it only takes a few seconds, as there is nothing to recompile. #306 will fix this issue.
