### ISSUE TITLE
cherab.info doesn't support https

### ISSUE THREAD

**Issue by dschwoerer** [cherab/core#313]
This breaks secure forwarding to https://cherab.github.io/documentation/

**Comment by CnlPepper** [comment]
I've reconfigured github pages and the domain DNS. HTTPS should now be supported. The URL is now cleaner too as github redirects to the cherab.info domain. Could you check it is working for you? If so, I'll close the issue.

**Comment by jacklovell** [comment]
Works for me

**Comment by dschwoerer** [comment]
Thanks, much nicer now :+1:
