### ISSUE TITLE
origin and direction parameters of SpectroscopicFibreOptic and SpectroscopicSightLine as optional

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#324]
Wouldn't it be better to have origin and direction parameters as optional in init methods of  [SpectroscopicFibreOptic](https://github.com/cherab/core/blob/dc74ba308c1e7a6ac179530ca8092b2e0d9f2e88/cherab/tools/observers/spectroscopy/fibreoptic.py#L66) and [SpectroscopicSightLine](https://github.com/cherab/core/blob/dc74ba308c1e7a6ac179530ca8092b2e0d9f2e88/cherab/tools/observers/spectroscopy/sightline.py#L57) as optional? The advantage would be that both classes could be treated as standard Raysect observers. I think the default value for origin can be Point3D(0, 0, 0) and for direction Vector3D(0, 0, 1), which results in unity affine transform and is more in a line with Raysect, where the transform is not requested as a parameter. 

When #322 is addressed it would be also possible to set default value to None and skip initialisation of origin and direction.

I'm sorry @vsnever this slipped through my hand during the review. I stumbled across it when I stared using SpectroscopicFibreOptic.

**Comment by vsnever** [comment]
Fixed in #323.
