### ISSUE TITLE
Making plasma radiation models pickleabe

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#326]
This could be quite useful for using same plasma radiation models for multiple simulations and for sharing radiation models. Sometimes it would be more convenient to send someone a pickled list of radiation models the plasma uses, instead of copy-pasting the script generating the model. I quickly tried to make ExcitationLine object pickleable and it is possible when the plasma is left out in the getstate/setstate methods (which doesn't matter since loaded models have to be connected to plasma to be used in an observation). Before I start working on it, I would like to get more opinions. Also I would then merge it with issue #294.

**Comment by vsnever** [comment]
I expect a problem with unpickling `Element/Isotope` instances of the `Line` until #246 is merged. 

I have not tried this but if I understand correctly, `self._plasma.composition.get(self._line.element, self._line.charge)` will raise `ValueError` for unpickled `ExcitationLine`, because the unpickled `line.element` will be an instant different from that in `plasma.composition`.

#246 should solve this issue by adding `__richcmp__` to `Element` and `Isotope` classes.

**Comment by Mateasek** [comment]
Thanks for warning @vsnever , I didn't see this one. I will wait for #246 to be accepted.

**Comment by Mateasek** [comment]
I checked out changes made in elements.pyx in PR #246 and added the possibility to pickle existing plasma radiation models. Once the PR #246 is accepted, I will make a PR. Thanks to @vsnever for the warning, I think you saved me a lot of time!

**Comment by CnlPepper** [comment]
Make sure you test this to death. Pickling cherab means dealing with weak references etc.. due to the notification system and there is a lot that could go wrong.

**Comment by Mateasek** [comment]
@CnlPepper I have a test, which builds a new plasma in a separate scenegraph with a new instance of atomic_data and adds models obtained with `pickle.loads(pickle.dumps(models))`. It seems to work, although now thinking about it the tests probably don't cover the case of a weakref to a non-existent object. I will try to improve it by removing the objects used to create the model list. 

Anyway, working on the PR I found out that only plasma objects have a weakref and this is why plasma is not returned/required by __getstate__/__setstate__ methods. This seems not to be a problem, since the models can be initialised without plasma or atomic_data. The references are updated when the modells are attached to a plasma object (in the plasma material __init__).

**Comment by Mateasek** [comment]
I made a draft PR #329 to show what I did and the attempt to test pickling.
