### ISSUE TITLE
Separate data sanity checks in _populate_cache() in plasma and beam models to generate accurate error messages.

### ISSUE THREAD

**Issue by vsnever** [cherab/core#331]
The error massages generated by some plasma models in `_populate_cache()` are misleading, see e.g. `BeamCXLine`:
https://github.com/cherab/core/blob/616c878bab2650a8e5e57540536fec0989b47eab/cherab/core/model/beam/charge_exchange.pyx#L273-L274
The affected plasma models are `ExcitationLine`, `RecombinationLine`, `TotalRadiatedPower` and `BeamCXLine`. 

The sanity checks should be separated to generate more helpful messages. The issue was noticed by @jacklovell  in cherab/solps#56.

**Comment by jacklovell** [comment]
Fixed by #333
