### ISSUE TITLE
Use log-log interpolation for the OpenADAS rates

### ISSUE THREAD

**Issue by vsnever** [cherab/core#339]
In #304, it was discovered that on coarse meshes, Raysect's cubic interpolators and in some cases Cherab's cubic interpolators give inaccurate and sometimes oscillating results. This was confirmed for ionisation and recombination rates as well as for impact excitation and recombination PECs. Switching to log-log interpolation seems to solve the problem.

We need to test all other rates as well to determine if they also should be interpolated on a log-log scale.

The fix for this issue will be implemented in #304.

**Comment by jacklovell** [comment]
Fixed by #304
