### ISSUE TITLE
Cleanup and fix demos prior to 1.3 release

### ISSUE THREAD

**Issue by vsnever** [cherab/core#342]
`demos/equilibrium/equilibrium.py` is missing `plt.show()` at the end.

`demos/emission_models/stark_broadening.py` is missing `plt.ioff()` prior to `plt.show()`.

`demos/openadas/adf15_available_transitions.py` does not run because `print_available_adf15_rates()` function is no longer available.

Some demo scripts have unused imports.

The "Code examples gallery" in documentation contains obsolete code.

I can fix the demo scripts, but how to be with the "Code examples gallery"? Some examples have `cherab_contrib` imports, etc.

**Comment by jacklovell** [comment]
I'll tidy these up before the release. The Code examples gallery has a mix of examples which no longer belong in this repo (e.g. rely on SOLPS or AUG data) and some which could be modernised, but not trivially. We'd intended to sort this at some point but didn't have the resources to do so. They've been broken for the existing release and not caused big headaches, so I don't think they should block 1.3.0.
