### ISSUE TITLE
Line Radiated Power as a LineShapeModel?

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#344]
Line Radiated Power feature could work in a simmilar way as the `TotalRadiatedPower` emission model. The advantage would be efficient and precide calculations of individual line intensities.

Some systems need to investigate line ratios, which are experimentally obtained either through system which integrate over a spectral band, as for example photomultipliers with bandpass filters, or through fitting of a spectral line shape.

In case of very narrow lines, the spectral resolution used in Cherab simulations has sometimes have to be very large, to limit numerical errors. The reason is real detectors integrate the received photons, but Cherab with a too large wavelength step can miss a line completely or the following integration can be numerically wrong due to bad sampling. Performing simulations can therefore be sometimes cumbersome, because there can be a number of lines to simulate in a wider wavelength range. The propose feature would remove such problems, but of course would have to be documented properly, to warn users, that the returned spectrum has a no real physical meaning.

From what I learned, the model could be efficiently added as a `LineShapeModel`, but I'm not completely sure if it should be grouped with other lines, to limit some confusion. It could be added alongside the `TotalRadiatedPower` into tools.

What do you think @vsnever and @jacklovell ?

**Comment by vsnever** [comment]
> In case of very narrow lines, the spectral resolution used in Cherab simulations has sometimes have to be very large, to limit numerical errors. The reason is real detectors integrate the received photons, but Cherab with a too large wavelength step can miss a line completely or the following integration can be numerically wrong due to bad sampling. 

Hi @Mateasek, the `add_gaussian_line ()` function uses Erf to integrate the Gaussian line shape over the spectral bin, so it is impossible to miss a line or calculate the wrong intensity regardless of the spectral resolution. Or did I not understand what you mean?

**Comment by Mateasek** [comment]
No, you understood correctly, I see now. So the error would not happen, thanks for pointing it out.

Anyway it could be a useful tool for calculations targeted only on line intensities, because you could skip the spectral part.

**Comment by vsnever** [comment]
The only two `PlasmaModel`s supporting a custom `LineShapeModel` are `ExcitationLine` and `RecombinationLine`. Therefore, you can simply add `LineRadiatedPower(PlasmaModel)`, which doesn't require a line shape. It will use `atomic_data.impact_excitation_pec()` and `atomic_data.recombination_pec()` just like `TotalRadiatedPower` uses `line_radiated_power_rate()` and `continuum_radiated_power_rate()`.

Alternatively, you can add a `DeltaFunctionLineShape` which will act like a Dirac delta function.

If you choose the second option, then I think it is better to keep this model along with other line shape models. Perhaps `lineshape.pyx` needs to be split into multiple files in`cherab/core/model/lineshape`, but that is a separate issue.

**Comment by Mateasek** [comment]
Yes, this is another option, but then this is what the `add_gaussian_line` will converge to, with decreasing spectral resolution, so actually we already have the requested functionality. I think I can close this issue. Thanks for helping me to realise this @vsnever.

**Comment by vsnever** [comment]
Probably, `add_gaussian_line()` will be slower than `add_deltafunction_line()`, but if performance is a priority, there are other options like pre-baking the spectral emissivity on a regular grid with `RegularGridEmitter`, https://github.com/raysect/source/pull/343 and `continuous` argument set to False.

**Comment by Mateasek** [comment]
Yes, if there is need for speed, then you should turn to other means as RTMs and the emitters you linked. Thanks again
