### ISSUE TITLE
Incomplete installation (cherab/__init__.py missing)

### ISSUE THREAD

**Issue by SimonPinches** [cherab/core#350]
Is this line really needed?

https://github.com/cherab/core/blob/0eb7454137b17bfbeca6d5e3eae4281f9cd4c157/setup.py#L109

We have faced problems with `lib/python3.8/site-packages/cherab/__init__.py` not being installed that are fixed by simply removing this line.

**Comment by jacklovell** [comment]
It's absolutely needed. Cherab is a large framework, of which `cherab-core` is only one part. Other submodules, such as `cherab-solps`, `cherab-jet` etc. are installed separately but into the same namespace so the framework as a whole looks like a single package. Removing core from the namespace would break all other Cherab modules.

As a namespace package, there is no `__init__.py` present: in fact PEP 420 requires this to be so. Adding one will turn Cherab into a regular package and likely break any submodules installed elsewhere (e.g. if a user does `pip install --user cherab-solps`).

**Comment by vsnever** [comment]
Hi @SimonPinches,
Is this the issue that required you to add `cherab/__init__py`, https://jira.iter.org/browse/IMAS-3826?

If so, I think the correct way to resolve it is to build Casper with Cython 3.0a5, see the README for https://github.com/cherab/solps for example.

Things will be easier when Cython 3.0 stable is released.

**Comment by SimonPinches** [comment]
Hi @jacklovell and @vsnever, thanks for your help.  It seems that building CHERAB and CASPER with Cython 3.0a5 has indeed solved the problem.
