### ISSUE TITLE
Improve Gaunt factor in Bremsstrahlung emission model

### ISSUE THREAD

**Issue by vsnever** [cherab/core#351]
This issue was briefly discussed at ITER Synthetic Diagnostic meeting, so I'm putting it here.

The applicability of the Gaunt factor, _G_, in Bremsstrahlung emission model, 
https://github.com/cherab/core/blob/0eb7454137b17bfbeca6d5e3eae4281f9cd4c157/cherab/core/model/plasma/bremsstrahlung.pyx#L99-L100
is very limited. It's missing the dependance on the wavelength and Zeff, which means that it can only be used within a limited range of the visible spectrum and only for the hot plasma, Te >~ 100 eV.

This Gaunt factor is compared with classical and Born approximations for the Gaunt factor in this ITER report, [3338YT](https://user.iter.org/default.aspx?uid=3338YT).

Briefly, _G<sub>class</sub>_ can be used if _α ≡ Zeff/(Te/Rd)<sup>1/2</sup>_ ≫ 1 and _G<sub>Born</sub>_ can be used if _α_ ≪ 1. Here:
_G<sub>class</sub>_ ≈ √3/π ln(2.e-4 · Te<sup>3/2</sup>[eV]/Zeff · λ[nm] + exp(π/√3))
and
_G<sub>Born</sub>_ ≈ 0.55 · ln(0.0018 λ[nm] Te[eV]) (low frequency limit).

The easiest solution would be to use a combination of _G<sub>class</sub>_ and _G<sub>Born</sub>_ in Cherab. The following two figures show _G<sub>class</sub>(Te, λ)_ and _G<sub>Born</sub>(Te, λ)_ as well as their difference (left plot) and combination, _G<sub>eff</sub>_, for Zeff = 1 and Zeff = 2. The vertical line shows _α=1/√2_ 

Using _G<sub>class</sub>_ for Te < 2 Rd Zeff <sup>2</sup> and _min_(_G<sub>class</sub>_, _G<sub>Born</sub>_) for Te > 2 Rd Zeff <sup>2</sup> will improve accuracy for low temperatures and in infrared spectral range.
![gaunt_factor_born_vs_classic_zeff_1 0](https://user-images.githubusercontent.com/22627041/149467006-1594db5a-3175-48c9-9f8e-f1f1a207ec8f.png)
![gaunt_factor_born_vs_classic_zeff_2 0](https://user-images.githubusercontent.com/22627041/149467072-2632d316-02cc-466e-98a3-72ccc2cfc8bf.png)

I would like to hear other opinions on this, so we probably continue discussions at ITER Synthetic Diagnostic meetings.

**Comment by vsnever** [comment]
We can also interpolate the Gaunt factor from Table 2 from T.R. Carson "Coulomb free-free Gaunt factors" 1988 Astron. Astrophys. 189 [319-324](https://adsabs.harvard.edu/pdf/1988A%26A...189..319C).

**Comment by Mateasek** [comment]
Hi @vsnever,

I remember Martin O'Mullane saing that they use the table in ADAS. I lost the reference, so I can't verify if it is the same work. Using interpolation of the table will probably result in more precise data right? In this case I think it would be preferable.Where would we store it? It should probably go to an atomic repo, right?

**Comment by vsnever** [comment]
Hi @Mateasek,

It's likely that we will need approximations in addition to the table for the values outside of the table's range. By the way I found more recent tables in M.A. de Avillez and  D. Breitschwerdt "Temperature-averaged and total free-free Gaunt factors for κ and Maxwellian distributions of electrons" [arXiv:1505.05608 [astro-ph.HE]](https://arxiv.org/abs/1505.05608), which cover broader range of parameters.

> Where would we store it? It should probably go to an atomic repo, right?

Yes, this is definitely the atomic data. I think we should create a base `FreeFreeGauntFactor` class and `MaxwellianFreeFreeGauntFactor` child class in cherab.core.atomic.gaunt_factors.pyx (κ-distributions can be implemented later on-demand). The child class will use the tables redistributed within the package in json format (probably in cherab/core/atomic/data). The base `AtomicData` class needs to be updated to include `free_free_gaunt_factor()` method, which unlike other methods should be implemented already in the base class.

**Comment by vsnever** [comment]
I checked that the Gaunt factors in Carson and de Avillez are identical, although in de Avillez they are calculated for a wider range of parameters.

Here is the comparison of the approximated (G<sub>eff</sub> from the previous figure) and the interpolated (de Avillez) Gaunt factors. It can be seen that the Born approximation works well at high Te and therefore can be used outside the interpolation range of the de Avillez's data.
![gaunt_factor_avillez_vs_approx_zeff_1 0](https://user-images.githubusercontent.com/22627041/149761855-d885ac31-5116-4e40-9b6a-7b59aac1be7b.png)

**Comment by jacklovell** [comment]
Fixed by #352
