### ISSUE TITLE
 Add charge exchange to TotalRadiatedPower 

### ISSUE THREAD

**Issue by wave46** [cherab/core#370]
I am going to make a synthetic bolometer diagnostic for WEST tokamak, based on SOLEDGE3X-HDG and ERO2 codes.
The plasma will contain deuterium as main ions and tungsten as impurities.

I was going to use `TotalRadiatedPower()` model from openadas module. However, there is no charge exchange taken into account in this model.

Should I try to add it by myself or were there any reasons of not to?

**Comment by jacklovell** [comment]
Hi @wave46. The `cherab.core.model.TotalRadiatedPower` model is the one you want. For each species (element, charge) it outputs the sum of the line radiation and recombination. You'll need to add a `TotalRadiatedPower` instance for all non-fully-ionised species in your plasma: D0 and whatever charge states of W you're considering.

For charge exchange, do you mean the radiation emitted through charge exchange reactions, or the heat flux on the bolometer foils from neutrals born through charge exchange reactions in the plasma? The former is likely to be insignificant compared with line emission + recombination. For the latter, Cherab does not implement any neutral particle dynamics, so this would be extremely effort-intensive to implement. You could probably get around it by working out what the neutral heat flux would be through some other code and then using a `cherab.tools.emitters.RadiationFunction` to pretend that this heat flux is a radiation-like power source with the correct intensity at the detector. I've had difficulties in getting codes to accurately predict the CX neutral flux though: neither KN1D nor SOLPS have been able to reproduce measurements of it in C-Mod, so treat any predictions you have with caution.

**Comment by wave46** [comment]
Hi @jacklovell.
Thank you for your answer!
I meant the first case, radiation emitted through CX reactions. To be more or less sure sure that these reactions are insignificant, should I compare their rates?
Also, I will probably have an access to ADAS database. Do you know, can using it instead of OpenADAS change the resulting radiation a lot, or in this case the difference is negligible?

**Comment by Mateasek** [comment]
Hi @wave46 
As far as I know, ADAS and Open-ADAS data should be identical, so there should be no need in switching to files stored in ADAS repositories, unless you produce your own rates, of course.

If you want to check the importance of CX radiated power, I would suggest calculating the power radiated per impurity particle. The power in line radiation, recombination and free-free radiation is connected to collisions with electrons and thus scales linearly with electron density. In same way, CX collisions are connected to collisions with neutrals, so power scales linearly with neutral density. Multiplying the PECs for the different mechanisms with the densities of the interacting species should show you if any region of plasma has a non-negligible radiated power by CX collisions. As @jacklovell said, in general I would expect the CX to be negligible and the distribution provided by any code to have limitted accuracy...

**Comment by vsnever** [comment]
Done in #455.
