### ISSUE TITLE
Bremsstrahlung trapezium rule bug

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#384]
I think that here we have a bug in the trapezium evaluation, don't we?

https://github.com/cherab/core/blob/c47a09ce7687bb01ebaca59e542924a28913b01a/cherab/core/model/plasma/bremsstrahlung.pyx#L77

I think that there should be (i + 1) term here, otherwise for the 1st iteration the `lower_wavelength` and `upper_wavelength` are equal, aren't they?

The line should look like:
` upper_wavelength = spectrum.min_wavelength + spectrum.delta_wavelength * (i + 1)`

**Comment by vsnever** [comment]
Hi @Mateasek, yes you are right. I fixed this in #352, but we decided to refactor the atomic data repository before applying this PR. So this bug deserves a separate fix.

**Comment by Mateasek** [comment]
I suspected you fixed it somewhere @vsnever , but looked into a wrong PRs.

**Comment by vsnever** [comment]
Fixed in #385.
