### ISSUE TITLE
Plasma inside/outside simulation tests

### ISSUE THREAD

**Issue by mattngc** [cherab/core#4]
* Early versions of CHERAB had an inside/outside test in some emission models. This allowed emission models to test if they should evaluate based on whether or not they are in the simulation domain.
* This was removed because it was deemed poor design. The emission models should always run but instead the plasma should return suitable values when outside its domain. i.e. ne = 0.
* In practice, even though the core plasma density interpolators can be configured to return 0 at the edge of their 1D range, the calculation never makes it this far if its outside the equilibrium domain. For example, a density point is requested outside of the equilibrium limits. The recipe electron_density = IsoMapper3D(psi, electron_density_psi) is used, and psi is called before the 1D electron density interpolator. In this case it raises a ValueError because its outside the 2D domain. In practice you can't turn on extrapolation for the equilibrium because diverted plasmas have a second region with normalised psi < 1. This effectively extrapolates the core plasma into the divertor. The only way around this is to use a last closed flux surface inside/outside test.
* Consider the example equilibrium plots attached.

![screenshot from 2017-09-27 10-42-07](https://user-images.githubusercontent.com/8628876/30906929-34bbc3bc-a371-11e7-8034-3cce8b889c0c.png)
![screenshot from 2017-09-27 10-42-20](https://user-images.githubusercontent.com/8628876/30906930-34bcfa2a-a371-11e7-993c-eb0dfce68f18.png)

**Comment by CnlPepper** [comment]
Hi Matt,

please revert #0e47119. The issue is addressed at the data preparation phase by configuring the plasma density to mask off regions outside the LCFS using the Blend2D function. For example:

unmasked_density = Isomapper2D(psi_function, density_profile)
density = Blend2D(Constant2D(0.0), unmasked_density, inside_lcfs)

This will return 0.0 outside the LCFS and the correct density profile inside.

Best regards,

Alex

**Comment by CnlPepper** [comment]
This code should go in user scripts and objects preparing plasma nodes, rather than core.

**Comment by mattngc** [comment]
Resolved by using new Blend2D class. Psi interpolation change reverted.
