### ISSUE TITLE
Need a utility function that constructs a velocity VectorFunction3D from underlying velocity profiles

### ISSUE THREAD

**Issue by mattngc** [cherab/core#55]
At the moment we tend to construct velocity functions from component profiles, like this:

```
flow_velocity = lambda x, y, z: Vector3D(y * flow_velocity_tor(x, y, z), - x * flow_velocity_tor(x, y, z), 0.) \
/ np.sqrt(x*x + y*y)
```

Although the flow velocity could be specified in terms of x, y, z, in reality its easier to specify it in terms of toroidal and poloidal functions. We need a utility that can combine a set of 1D functions for each component and map them into a 3D function.

**Comment by CnlPepper** [comment]
Doesn't this already exist: https://github.com/cherab/core/blob/74e69ed6a0339362baa2f89d02a74c74d8d43ea2/cherab/core/math/function/vectorfunction3d.pyx#L103

**Comment by CnlPepper** [comment]
I think we already have the chain of functions to achieve this quickly: 
https://github.com/cherab/core/blob/74e69ed6a0339362baa2f89d02a74c74d8d43ea2/cherab/core/math/mappers.pyx#L181

**Comment by CnlPepper** [comment]
Hmm actually I see what you mean, calculating the poloidal vector is more tricky. Would need to obtain the direction vector from the gradient in psi (ie use r and z field components) and scale by the poloidal flow magnitude.

**Comment by mattngc** [comment]
Yeah, its because our demos only specify the toroidal velocity, but strictly speaking this isn't sufficient. We need to specify the poloidal component as well. Then we need a reference to the equiibrium to get the component basis vectors, etc.

**Comment by mattngc** [comment]
Did some work on this in 5d00cd97dda0fa2ff00e73f0d87341b560671c52 and 73125a9fc96a04a209496ecc92e055a9ebf49b06. Will merge as is because some users need it.

**Comment by mattngc** [comment]
Just merged this work, needs documentation. Issue considered fixed.
