### ISSUE TITLE
Need BlendVector2D and BlendVector3D functions

### ISSUE THREAD

**Issue by CnlPepper** [cherab/core#64]
The equilibrium map_vector2d/3d methods current use a different pattern to the scalar 2d/3d map methods. This is because there are no blend function for vectors. We need to add these and modify the efit equilibrium handler.

**Comment by jacklovell** [comment]
Raysect has implemented Blend2D and Blend3D vector functions, and these are now used in the equilibrium map_vector2d/3d methods.
