### ISSUE TITLE
Should the vertex argument in AxisymmetricVoxel be a Nx2 array?

### ISSUE THREAD

**Issue by mattngc** [cherab/core#67]
Currently the vertices argument is a list/tuple of Point2Ds. Elsewhere in the framework it is common to see Nx2 arrays as arguments, so maybe we should refactor this for consistency.

**Comment by jacklovell** [comment]
This seems sensible to me. Can you make this change in such a way that it's still possible to provide a sequence of Point2Ds too, to avoid breaking existing code?

**Comment by mattngc** [comment]
Yes, this should be doable. As long as its validated and handled appropriately it should be fine.

**Comment by jacklovell** [comment]
Fixed by #157
