### ISSUE TITLE
import error for core.math.slice in development branch

### ISSUE THREAD

**Issue by drsmith48** [cherab/core#72]
For the development branch, `python setup.py build` is successful, but `import cherab.core` (in build/lib) fails with this error:

```python
>>> import cherab.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/drsmith/repos/core/build/lib.macosx-10.7-x86_64-3.7/cherab/core/__init__.py", line 21, in <module>
    from .species import *
  File "cherab/core/math/function/vectorfunction2d.pxd", line 23, in init cherab.core.species
    cdef class VectorFunction2D:
  File "/Users/drsmith/repos/core/build/lib.macosx-10.7-x86_64-3.7/cherab/core/math/__init__.py", line 29, in <module>
    from .slice import Slice2D, Slice3D
ModuleNotFoundError: No module named 'cherab.core.math.slice'
```

I noticed that the build process did not generate a file `core/math/slice*.so` or `slice.c`.  In fact, the compilation and linking steps during the build make no reference to `slice.*`.  Also, I noticed that `cherab.egg-info/SOURCES.txt` does not list `core/math/slice.c`, so I suspect the Cython build somehow skips `slices.*`.  My platform is MacOS 10.13.6 and a conda env with Python 3.7.2 and Cython 0.29.5.

**Comment by CnlPepper** [comment]
Could you try running the dev/clean.sh script, delete the build folder and then retry? It is possible there is some stale state. Performing a git pull just to be sure would be useful too.

**Comment by CnlPepper** [comment]
The slice source files are definitely in the development tree: https://github.com/cherab/core/tree/development/cherab/core/math

**Comment by drsmith48** [comment]
I can build and import now.  I deleted the build folder, ran clean.sh, and I added --use-cython in the build command.  Thanks!

**Comment by CnlPepper** [comment]
Glad it worked! :)
