### ISSUE TITLE
Add samplers which take an array of points

### ISSUE THREAD

**Issue by jacklovell** [cherab/core#88]
Following on from https://github.com/raysect/source/issues/272, I'm raising this issue to discuss the best way to implement sampling `FunctionXD` objects on a user-provided list of points. The current `sampleXd` functions in Cherab are for a specific use case: sampling over a regular grid defined by its extents and number of samples. There is a need for other ways of sampling, particularly when the user already has an array of points at which they want to sample.

The following should be implemented (examples given are 2D, but also extend to 3D):
1. For an array of points (xi, yi), return an array f(xi, yi) (i.e. one sample for each point).
2. For a grid defined by coordinates xi (x coordinate of each column) and yi (y coordinate of each row), return a 2D array of samples for every point in the grid.

For 1D functions, only the first of these needs to be implemented: the result will always be 1D. For  the 2D case, inspiration is taken from [scipy's RectbivariateSpline call method](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectBivariateSpline.__call__.html), which can be evaluated both on a grid (`grid=True`) and on individual coordinates (`grid=False`). In the first case Scipy expects 1D arrays xi and yi and returns a 2D array. In the second case Scipy broadcasts the x and y input arrays and returns the broadcasted result, which may be 1D if both arrays are 1D.

I'm not sure if there's an additional case for 3D. The only ones I can think of are a 3D array produced from 3 1D arrays of x, y, z and the broadcasted array produced from up-to-3D arrays of xi, yi, zi.

Since I've found the scipy convention confusing and error-prone in the past, I propose providing completely different functions for each case. For example, a `sample2d_points` would correspond to implementation of 1), and a `sampled_2d_grid` would correspond to implementation of 2). There would be analogously-named functions for 3D sampling, and a single `sample1d_points` too. Case 2) is essentially the same as the existing `sampleXD` functions, except that rather than "range tuples" the explicit values are passed in, which enables non-regular grids.

Also, the current `sampleXd` functions return the points at which the function has been sampled, as well as the function values. That's clearly not necessary for these new functions (they'd just be returning the input arguments), so is it OK to change the output from a tuple of arrays to just a single array for these new functions?

**Comment by jacklovell** [comment]
Should be fixed once #90 is merged

**Comment by mattngc** [comment]
Resolved now that PR #90 has been merged.
