### ISSUE TITLE
Validate number of positional arguments in FunctionXDs

### ISSUE THREAD

**Issue by mattngc** [cherab/core#93]
I've noticed its easy to get miss-matching functions in CHERAB because of the way the auto wrap functions work. Take this case I just stumbled across as an example:

```
plasma.b_field = equilibrium.b_field
```

Here `equilibrium.b_field` is a MagneticField(VectorFunction2D). But `plasma.b_field` is expecting a VectorFunction3D. The autowrap function correctly identifies it is not a VectorFunction3D, but then wraps it in a PythonVectorFunction3D.

As an improvement we should check the number of positional arguments in each PythonFunction*D with the inspect module. For example:

```
>>> from inspect import signature
>>> 
>>> def someMethod(self, arg1, kwarg1=None):
...     pass
>>> sig = signature(someMethod)
>>> sig.parameters
mappingproxy(OrderedDict([('self', <Parameter "self">), ('arg1', <Parameter "arg1">), ('kwarg1', <Parameter "kwarg1=None">)]))
>>> len(sig.parameters)
3
>>> for param in sig.parameters.values():
...     if (param.kind == param.POSITIONAL_OR_KEYWORD):
...         print('Param:', param)
... 
Param: self
Param: arg1
Param: kwarg1=None
```

**Comment by CnlPepper** [comment]
Looks like a good idea provided we can ensure it is robust.

**Comment by CnlPepper** [comment]
This issue will need to be pushed upstream. The function and autowrap code are imported from Raysect.

**Comment by mattngc** [comment]
ah, whoops. Yes you are right. I'll raise this over on Raysect.
